= Preface

== Purpose

This document describes the openEHR Resource Model, a model of any 'authored resource', including identification, meta-data, annotations and translations.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].

== Status

The content of this specification were separated out from the {openehr_rm_common}[Common IM specification], in order to allow re-use by any openEHR component.

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_resource}[{openehr_resource}].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list].

Issues may be raised on the {openehr_jira_prs_base}[specifications Problem Report tracker].

To see changes made due to previously reported issues, see the {openehr_jira_crs_base}[{component} component Change Request tracker].

== Conformance

Conformance of a data or software artifact to an openEHR Reference Model specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal, derivations from the Reference Model, ITS conformance indicates RM conformance.

