[cols="2,3", frame=none, grid=rows]
|===
2+^h|*BMM_PARAMETER_TYPE*

2+a|Definition of a generic parameter in a class definition of a generic type.

2+|Inherits: xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS], xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY], xref:BASE:bmm:core_package.adoc#_bmm_type_class[BMM_TYPE], xref:BASE:bmm:core_package.adoc#_bmm_unitary_type_class[BMM_UNITARY_TYPE]

2+h|*Constants*

|*Bmm_internal_version*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}` [1..1]
a|Current internal version of BMM meta-model, used to determine if a given schema can be processed by a given implementation of the model. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS]_

|*Schema_name_delimiter*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"::"` [1..1]
a|Delimiter used to separate schema id from package path in a fully qualified path. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS]_

|*Package_name_delimiter*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"."` [1..1]
a|Delimiter used to separate package names in a package path. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS]_

|*Bmm_schema_file_extension*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}".bmm"` [1..1]
a|Extension used for BMM files. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS]_

|*Entity_metatype_simple*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"simple_entity"` [1..1]
a|Category of a simple entity, other than enumerated types. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_metatype_enumeration*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"enumeration_entity"` [1..1]
a|Category of any enumeration entity. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_metatype_generic*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"generic_entity"` [1..1]
a|Category of any generic entity that is not a container entity. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_metatype_parameter*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"generic_parameter_entity"` [1..1]
a|Category of a formal generic parameter entity. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_metatype_container*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"container_entity"` [1..1]
a|Category of any container entity. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_category_modifier_abstract*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"abstract"` [1..1]
a|Category modifier indicating an entity is formally defined as abstract, i.e. not-directly instantiable within a BMM model. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_category_modifier_primitive*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"primitive"` [1..1]
a|Category modifier indicating that an entity is considered to be primitive within the type system of a given BMM model. Has no semantic consequences within the BMM. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

2+h|*Attributes*

|*name*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Name of the parameter, e.g. 'T' etc. The name is limited to 1 character and upper-case.

|*type_constraint*: `xref:BASE:bmm:core_package.adoc#_bmm_defined_type_class[BMM_DEFINED_TYPE]` [0..1]
a|Optional conformance constraint that must be another valid class name.

|*inheritance_precursor*: `xref:BASE:bmm:core_package.adoc#_bmm_parameter_type_class[BMM_PARAMETER_TYPE]` [0..1]
a|If set, is the corresponding generic parameter definition in an ancestor class.

2+h|*Functions*

|_(abstract)_ *entity_category* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Generate a category code-string to use in visualisation, that indicates:

* _entity meta-type_: simple &#124; enumerated &#124; generic &#124; generic_effective &#124; parameter
* _abstract modifier_ - abstract status
* _primitive modifier_ primitive status

The code is structured as:

----
entity_metatype [ '-' abstract_modifier ] [ '-' primitive_modifier ]
---- +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*entity_metatype* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Meta-type of a container type is `Entity_metatype_generic_parameter`.

|*is_abstract* (): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|Result = `False` - generic parameters are understood by definition to be non-abstract.

|*is_primitive* (): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` +
 +
__Post_validity__: `Result = base_class.is_primitive` [1..1]
a|Result = `False` - generic parameters are understood by definition to be non-primitive.

|*effective_base_class* (): `xref:BASE:bmm:core_package.adoc#_bmm_class_class[BMM_CLASS]` [1..1]
a|The effective conformance type of this parameter, or the 'Any' class if none.

|*type_name* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Result is `_name_`.

|*has_subtypes* (): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|True if `_effective_conforms_to_type.base_class.has_descendants_`.

|*subtypes* (): `xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>` [1..1]
a|Result is `_effective_conforms_to_type.base_class.all_descendants_` .

|*flattened_type_list* (): `xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>` [1..1]
a|Result is either `_flattened_conforms_to_type.flattened_type_list_` or the `Any` type.

|*type_signature* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Signature form of the open type, including constrainer type if there is one, e.g. `T:Ordered`.

|*flattened_conforms_to_type* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Result is either `_conforms_to_type_` or `_inheritance_precursor.flattened_conforms_to_type_`.

|*effective_conforms_to_type* (): `xref:BASE:bmm:core_package.adoc#_bmm_class_class[BMM_CLASS]` [1..1]
a|Generate ultimate conformance type, which is either `_flattened_conforms_to_type_` or if not set, `Any`.

2+h|*Invariants*

2+a|__Inv_generic_name__: `name.count = 1 and name.is_upper`

|===
