[cols="2,3", frame=none, grid=rows]
|===
2+^h|*BMM_CONTAINER_TYPE*

2+a|Type that specifies linear containers with a generic parameter corresponding to the type of contained item, and whose container type is a generic type such as `List<T>`, `Set<T>` etc.

2+|Inherits: xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS], xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY], xref:BASE:bmm:core_package.adoc#_bmm_type_class[BMM_TYPE]

2+h|*Constants*

|*Bmm_internal_version*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}` [1..1]
a|Current internal version of BMM meta-model, used to determine if a given schema can be processed by a given implementation of the model. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS]_

|*Schema_name_delimiter*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"::"` [1..1]
a|Delimiter used to separate schema id from package path in a fully qualified path. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS]_

|*Package_name_delimiter*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"."` [1..1]
a|Delimiter used to separate package names in a package path. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS]_

|*Bmm_schema_file_extension*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}".bmm"` [1..1]
a|Extension used for BMM files. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_definitions_class[BMM_DEFINITIONS]_

|*Entity_metatype_simple*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"simple_entity"` [1..1]
a|Category of a simple entity, other than enumerated types. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_metatype_enumeration*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"enumeration_entity"` [1..1]
a|Category of any enumeration entity. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_metatype_generic*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"generic_entity"` [1..1]
a|Category of any generic entity that is not a container entity. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_metatype_parameter*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"generic_parameter_entity"` [1..1]
a|Category of a formal generic parameter entity. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_metatype_container*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"container_entity"` [1..1]
a|Category of any container entity. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_category_modifier_abstract*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"abstract"` [1..1]
a|Category modifier indicating an entity is formally defined as abstract, i.e. not-directly instantiable within a BMM model. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*Entity_category_modifier_primitive*: `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]{nbsp}={nbsp}"primitive"` [1..1]
a|Category modifier indicating that an entity is considered to be primitive within the type system of a given BMM model. Has no semantic consequences within the BMM. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

2+h|*Attributes*

|*container_class*: `xref:BASE:bmm:core_package.adoc#_bmm_generic_class_class[BMM_GENERIC_CLASS]` [1..1]
a|The type of the container. This converts to the `_root_type_` in `BMM_GENERIC_TYPE`.

|*base_type*: `xref:BASE:bmm:core_package.adoc#_bmm_unitary_type_class[BMM_UNITARY_TYPE]` [1..1]
a|The target type; this converts to the first parameter in `_generic_parameters_` in `BMM_GENERIC_TYPE`.

2+h|*Functions*

|_(abstract)_ *entity_category* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Generate a category code-string to use in visualisation, that indicates:

* _entity meta-type_: simple &#124; enumerated &#124; generic &#124; generic_effective &#124; parameter
* _abstract modifier_ - abstract status
* _primitive modifier_ primitive status

The code is structured as:

----
entity_metatype [ '-' abstract_modifier ] [ '-' primitive_modifier ]
---- +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_entity_class[BMM_ENTITY]_

|*entity_metatype* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Meta-type of container type is `Classifier_metatype_container`.

|*is_abstract* (): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|True if `_base_type.is_abstract_` or `_container_type.is_abstract_`.

|*is_primitive* (): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` +
 +
__Post_validity__: `Result = base_class.is_primitive` [1..1]
a|True if `_base_class.is_primitive_`. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_type_class[BMM_TYPE]_

|*effective_base_class* (): `xref:BASE:bmm:core_package.adoc#_bmm_class_class[BMM_CLASS]` +
 +
__Post_validity__: `Result = base_type.base_class` [1..1]
a|Result is `_base_class_` of `_base_type_`.

|*type_name* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Return full type name, e.g. `List<ELEMENT>`.

|*has_subtypes* (): `xref:BASE:foundation_types:primitive_types.adoc#_boolean_class[Boolean]` [1..1]
a|Determine if there are any type substitutions.

|*subtypes* (): `xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>` [1..1]
a|Result is all permutations of current container type and its descendants with the current `_base_type_` and its descendants.

|*flattened_type_list* (): `xref:BASE:foundation_types:structure_types.adoc#_list_class[List]<xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]>` [1..1]
a|Completely flattened list of type names, flattening out all generic parameters.

|*type_signature* (): `xref:BASE:foundation_types:primitive_types.adoc#_string_class[String]` [1..1]
a|Signature form of the type, which for generics includes generic parameter constrainer types E.g. `Interval<T:Ordered>`.

Generally useful for display purposes. +
_Inherited from xref:BASE:bmm:core_package.adoc#_bmm_type_class[BMM_TYPE]_
|===
