= Amendment Record

[cols="1,6,2,2", options="header"]
|===
|Issue|Details|Raiser|Completed

|[[latest_issue]]3.1.0
|Add feature elements `BMM_ROUTINE`, `BMM_VALUE_RETURNING` and descendants; +
 Change `BMM_PROPERTY._is_mandatory_` to `BMM_MUTABLE._is_nullable_` (reversed Boolean sense); +
 Made `BMM_PACKAGE_CONTAINER` abstract; +
 Moved `_name_` to `BMM_MODEL_ELEMENT`, replacing `_name_` in `BMM_CLASS`, `BMM_PACKAGE`, `BMM_PROPERTY`, and `_model_name_` in `BMM_MODEL`; +
 Marked `BMM_PROPERTY._is_computed_` as obsolete (to be phased out); +
 Add `BMM_PROPERTY._is_composition_` to distinguish part/whole from associations.
|T Beale
|[[latest_issue_date]]15 Sep 2018

|3.0.0
|Separate `P_BMM` model and syntax to BMM Persistence specification; +
 refactor / tighten class model: +
 rename `BMM_GENERIC_PARAMTER` to `BMM_PARAMETER_TYPE`; +
 remove `BMM_OPEN_TYPE`; remove `BMM_TYPE_ELEMENT`; +
 add new type `BMM_DEFINED_TYPE` as parent of `BMM_SIMPLE_TYPE` and `BMM_GENERIC_TYPE`; +
 add new type `BMM_UNITARY_TYPE` as parent of `BMM_DEFINED_TYPE` and `BMM_PARAMETER_TYPE`; +
 redefine `BMM_CLASS._ancestors_` to be of type `BMM_DEFINED_TYPE`; +
 redefine `BMM_PARAMETER_TYPE._conforms_to_` to `_type_constraint_` of type `BMM_DEFINED_TYPE`; +
 correct `BMM_CLASS._immediate_descendants_` to be of type `List<BMM_CLASS>`; +
 rename `BMM_CLASSIFIER` to `BMM_ENTITY`; +
 Support generic types as class ancestors; +
 Remove archetype-related meta-data.
|T Beale
|12 May 2018

|2.2.2
|Improve and update introductory text in the Overview section.
|E Sundvall, +
 T Beale
|03 Nov 2017

|2.2.1
|Remove `BMM_CLASSIFIER._conformance_type_name_`; +
 Constrain `BMM_GENERIC_PARAMETER._name_` to one character and upper case.
|C Nanjo, +
 T Beale
|02 Mar 2017

|2.2.0
|Rename `BMM_CLASSIFIER._as_type_string_` to `_type_name_` and `_as_conformance_type_string_` to `_conformance_type_name_`. +
 Move and rename `BMM_TYPE._as_display_type_string_` to `BMM_CLASSIFIER._type_signature_`. Add redefinitions in relevant descendant classes. +
 Rename `BMM_SIMPLE_TYPE_OPEN` to `BMM_OPEN_TYPE`. +
 Add new class `BMM_TYPE_ELEMENT` in preparation for BMM 3 refactoring. +
 Rename `BMM_SCHEMA` to `BMM_MODEL`.
|T Beale
|20 Jun 2016

|2.1.0
|Initial writing based on ADL Workbench implementation.
|T Beale
|08 Feb 2016

|===
