= Overview

== Introduction

One of the key needs in any open computing environment is a computable representation of its own models, for a number of purposes, including reasoning about them, performing validation and consistency checking, building software and generating documentation. This is particularly true of openEHR, where a further need is to be able to validate archetypes and templates with respect to the reference model, and also to validate runtime instance data against operational templates and the reference model.

A number of computable representations of the openEHR published models have been available in the past. Unfortunately the standards and tools available for model representation in ICT in general remain problematic.

== Requirements

The key requirements for human- and machine-readable models are as follows:

* a primary computable expression of the reference model as published in the specification documents
** functionally, the formalism and tooling need to support static class models, including generic classes, multiple inheritance, class invariants, pre-conditions and post-conditions (i.e. 'design by contract' or DbC elements)
** ideally this expression would be defined either
*** within a UML tool, and exported in a usable form; or
*** within some other editor that makes it easy to maintain.
** this expression should be the basis for published documentation of the specifications;
** this expression should also support machine validation / compilation to ensure the model is valid.
* one or more data serialisation forms, derived from the primary expression
** at least XML needs to be supported, but other formats such as JSON and the openEHR dADL may also be supported.

== Current State of the Art

One would think that the ICT industry would have fully computable representations of models and diagramming solved, but it is not yet the case. UML 2.x and its associated serialisation format XMI 2.x should in theory mean that complete, interoperable machine expressions of object models would be available in all tools. It will probably eventually come to pass, but a number of obstacles remain to date:

* the UML 2.x specifications are exceedingly complex (see OMG site for specifications; UML 2.1.2 'superstructure' = 738pp; UML 2.1.2 'infrastructure' = 224pp);
* the XMI 2.x specification is correspondingly complex, which seems to have so far prevented reliable tool interoperability;
* the Design By Contract (DbC) concept is supported via the use of OCL 2.0 constraints in class models, although there are semantic holes, e.g. proper semantics through inheritance;
* for some, XML-schema represents a way of expressing object models, but in fact is not semantically suitable for this purpose. It can be and is used (including in openEHR) as a derivative serialisation representation, but from the point of view of specification, it is deficient in having non-object-oriented inheritance semantics, no generic classes, no representation of non-data members, and only marginal support for design by contract.

Experience with various UML tools (up till 2015) highlighted the following problems:

* poor support for OCL and design by contract in most tools;
* variable support for generic (i.e. template) classes; even those tools that properly implement the UML 2.5 specification are still very hard to use for defining generic classes because of problems in the specification that remain unaddressed;
* variable support for XSD generation across tools, where the results are wildly wrong in some tools;
* in some tools, it is impossible to define an abstract formal model. The only option is to select a programming language profile such as Java or C# and thus get locked into the limitations of those languages (messy type systems, weak inheritance semantics, language-specific notion of types such as `Array<T>`, `List<T>`, etc.).

== Design

The Basic Meta-Model provides a model of object models in the data point of view. It is designed to enable both human authoring and machine extraction (e.g. from a UML tool or programming language classes) of textual schemas. This specification defines a BMM object model, i.e. the in-memory object structure of a BMM, and also an object model for a serialised form. The latter enables serialisation of a BMM into a concrete syntax such as ODIN, JSON or XML. In the future an abstract syntax serialisation may be developed in the style of OMG IDL (Interface Definition Language) or similar.

The BMM model packages are as follows:

* `rm_access`: the interface to most features including schema load/reload, generally used by an application as a reflection library;
* `core`: the core BMM classes used for in-memory representation of an object model;
* `persistence`: a simplified version of the core classes prefixed with `P_BMM_`, used for persistence and human authoring, which allow file (i.e. schema) inclusion and re-use.

The `P_BMM_*` classes perform two functions. Firstly, they are a modified and simplified version of the `BMM_*` classes that enable for example symbolic referencing via class names, syntactical type names to be used etc, rather than the full explision of fine-grained objects that would result from a direct serialisation of `BMM_*` classes. This is what enables the BMM file format to be easily readable and editable by human users.

The second is that BMM files work as schemas that support schema inclusion and therefore re-use, in a similar manner to the XML schema languages. Thus, a single logical BMM model can be expressed as a _number_ of `BMM` schema files which are actually `P_BMM` serialisations. A schema reading component has to perform the schema inclusions and ultimately `BMM_*` object instantiations to obtain the in-memory form of the model.

The packages are illustrated below.

[.text-center]
.Package Overview
image::{uml_export_dir}/diagrams/BMM-packages.svg[id=package_overview, align="center"]

The normal use of BMM is as follows:

* create a BMM schema in the form of one or more files, using the `P_BMM_` form of the model expressed in ODIN. This is easy to understand by using the link:../example/example.bmm[example schema] and/or copying other examples;
* locate these files in a suitable place for use with a tool such as the {openehr_awb}[openEHR ADL Workbench] and {linkehr}[LinkEHR].

== A Note on Language

The elements of meta-models are sometimes named confusingly in the literature and within various programming language technologies. In this specification, we have used the following terms:

feature (of a class):: any stored or computed element of a class;
property:: a stored class feature; also known as 'attribute';
routine:: a computed class feature;
function:: a routine that computes and returns a value; typically causes no side-effects in the object;
procedure:: a routine that performs a computation; typically has side-effects;
generic (class or type):: a kind of class or type that has parameters of other types; known as 'template' type in some programming languages.
