= BMM Entities

== Overview

The following UML diagram shows the BMM model of _classes_ and _types_, collectively known as _entities_.

[.text-center]
.base.bmm.core Package - Entities
image::{uml_export_dir}/diagrams/BASE-bmm.core-entities.svg[id=core_entities, align="center"]

The general structure of a BMM consists of a set of classes, whose features (properties, routines) are each typed by an instance of `BMM_TYPE`. The following shows the typing of properties. Structures specific to generic and container types are shown in relevant sections below. 

[.text-center]
.BMM entities
image::diagrams/bmm_entities.svg[id=bmm_entities, align="center"]

== The Class / Type Division

One of the foundational distinctions in the BMM is between _class_ and _type_, in common with the type systems of the modern forms of most object-oriented languages, but in contrast to the UML meta-model. Classes are _definitional_ entities, while 'type' has two meanings: 

* as the static (design time) type of a class feature (property or function result), and 
* as the dynamic (run-time) type of the object referred to by or computed by that feature. 

In a static model, types are references. For simple types, they refer to the corresponding simple class definition, but for generic types, they refer to a particular usage of a generic class definition. A generic class may generate numerous types.

This central division is reflected in the two classes `BMM_CLASS` and `BMM_TYPE`. The common parent class `BMM_ENTITY` defines a small number of properties that classify both classes and types in a model: `_entity_metatype_`, `_is_abstract_` and `_is_primitive_`. These are combined to produce a String classifier `_entity_category_`, which can be used to help visualise elements of a BMM model.

The Boolean attribute `_is_abstract_` on an entity indicates an abstract class in a BMM model, or a type based on an abstract class. The attribute `_is_primitive_` indicates that a class in a BMM model is considered to be part of a primitive type set (typically corresponding to primitive types in another type system); for types, it is derived from the setting of the `_base_class_`. Primitive status has no effect on BMM model semantics, and is provided as a convenience for visualisation and type-system mapping.

The taxonomy represented by `BMM_ENTITY._entity_category_` is illustrated below.

[.text-center]
.BMM entity taxonomy
image::diagrams/bmm_entity_taxonomy.svg[id=bmm_entity_taxonomy, align="center"]

== Class Definitions

include::{uml_export_dir}/classes/bmm_entity.adoc[]
