include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ars Semantica; openEHR Foundation Management Board.

=== Contributors

This specification has benefited from formal and informal input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following people for their contributions.

* Silje Ljosland Bakke, RN, National ICT health trust, Norway
* Diego Boscá, IBIME, Technical University Valencia, VeraTech for Health, Spain
* Sebastian Garde PhD, Ocean Health Systems, Germany
* Grahame Grieve, Health Intersections, Australia
* Heather Leslie MD, FRACGP, FACHI, Ocean Health Systems, Australia
* Ian McNicoll MD, FreshEHR UK
* Andrew Patterson PhD, LLM, Federation Health Software, Australia

=== Supporters

The work reported in this paper has been funded in by the following organisations:

* University College London - Centre for Health Informatics and Multi-professional Education (CHIME);
* Ocean Informatics.

Special thanks to David Ingram, Emeritus Professor of Health Informatics at UCL, who provided a vision and collegial working environment ever since the days of GEHR (1992).




ifdef::package_qualifiers[]
endif::[]
== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.


ifdef::package_qualifiers[]
:pkg: org.openehr.base.resource.
endif::[]

:sectnums!:

include::partial$amendment_record.adoc[]
