= Time Types

== Overview

Two packages of time types are defined in this specification: the `foundation_types.time` package and the `foundation_types.iso8601_time` package. The first group are assumed to be available within the implementation environment, and normally correspond to either built-in types or standard library classes. The second set are conrete types based on the ISO 8601 time standard, which supports partial dates, times, and complex durations, all of which are needed in the biomedical and clinical domains. These classes have a `String` physical representation, and also inherit from the `IDate` etc classes.

The two packages are shown below.

[.text-center]
.foundation_types.time and base_types/iso8601_time packages
image::{uml_export_dir}/diagrams/BASE-foundation_types.time.svg[id=foundation_types_time_types, align="center"]

== Primitive Time Types (assumed)

The classes in the `foundation_types.time` package are divided into interface classes `IDate` etc, and concrete primitive types `Date`, `Time` etc, which are assumed to have some 'native' data representation such as a long integer or similar. The separation is a clarifying device for this specification. It is not assumed that the classes `IDate` etc literally exist in a given implementation environment.

== ISO 8601 Types

The set of ISO 8601 based types define dates and times with a `String` representation (as per ISO 8601), and the ISO 8601 'partial' and 'extended' semantics. They are defined as descendents of the native types described above, and add the necessary elements required for ISO 8601.

ISO 8601 semantics not used in these types include:

* "expanded" dates, which have year numbers of greater than 4 digits, and may be negative; in openEHR, only 4-digit year numbers are assumed;
* the `YYYY-WW-DD` method of expressing dates (since this is imprecise and difficult to compute with due to variable week starting dates, and not required in health);
* partial date/times with fractional minutes or hours, e.g. `hh,hhh` or `mm,mm`; in openEHR, only fractional seconds are supported;
* the interval syntax. Intervals of date/times are supported in openEHR, but their syntax form is defined by ADL, and is standardised across all comparable types, not just dates and times.

Deviations from the published standard include the following:

* durations are supposed to take the form of `PnnW` or `PnnYnnMnnDTnnHnnMnnS`, but in openEHR, the W (week) designator can be used in combination with the other designators, since it is very common to state durations of pregnancy as some combination of weeks and days.
* partial variants of `Iso8601_date_time` can include missing hours, days and months, whereas ISO 8601:2004 (section 4.3.3 c) only allows missing seconds and minutes. The reasons for this deviation are:
** the same deviation is used in HL7v2 and HL7v3 TS (timestamp) type, i.e. there are data in existing clinical systems matching this specification;
** in a typed object model, this deviation is more sensible anyway; the ISO 8601 rule is most likely a limitation of the purely syntactic means of expression. In real systems where a timestamp/date-time is specified in a screen form, it makes sense to allow it to be as partial as possible, rather than artifically restricted to only missing seconds and minutes.
* the time `24:00:00` (or `240000`) is not allowed anywhere, whereas in ISO 8601:2004 it appears to be legal at least for times. This deviation is also appears to be used in HL7v2 and HL7v3 (where midnight is defined as the time `00:00:00`), and is preferable to the documented standard, since a date/time with time of `24:00:00` is really the next day, i.e. the date part is then incorrect.

See <<ISO_8601>> and the official ISO standard for ISO 8601 details. Note that in the date, time and date_time formats shown below, 'Z' and 'T' are literals.  In the duration class shown below, 'P', 'Y', 'M', 'W', 'D', 'H', 'S' and 'T' are literals.

== Derived Interval / Time Types

A number of useful types may be generated from the Date/time classes and the Interval classes. These are shown in blue on the following diagram.

[.text-center]
.Useful time interval types
image::{uml_export_dir}/diagrams/BASE-foundation_types.time-intervals.svg[id=foundation_types_time_intervals, align="center"]

== Class Definitions

include::{uml_export_dir}/classes/time_definitions.adoc[]

include::{uml_export_dir}/classes/temporal.adoc[]

include::{uml_export_dir}/classes/idate.adoc[]

include::{uml_export_dir}/classes/itime.adoc[]

include::{uml_export_dir}/classes/idate_time.adoc[]

include::{uml_export_dir}/classes/iduration.adoc[]

include::{uml_export_dir}/classes/itimezone.adoc[]

include::{uml_export_dir}/classes/date.adoc[]

include::{uml_export_dir}/classes/time.adoc[]

include::{uml_export_dir}/classes/date_time.adoc[]

include::{uml_export_dir}/classes/duration.adoc[]

include::{uml_export_dir}/classes/timezone.adoc[]

include::{uml_export_dir}/classes/iso8601_type.adoc[]

include::{uml_export_dir}/classes/iso8601_date.adoc[]

include::{uml_export_dir}/classes/iso8601_time.adoc[]

include::{uml_export_dir}/classes/iso8601_date_time.adoc[]

include::{uml_export_dir}/classes/iso8601_duration.adoc[]

include::{uml_export_dir}/classes/iso8601_timezone.adoc[]
