= Preface

== Purpose

This document describes the openEHR Base Types, whose semantics are used by all other openEHR specifications.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Research groups using openEHR, ISO 13606, archetypes and related technologies;
* The open source healthcare community;
* Solution vendors.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_base_types}.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira}/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

