= Preface

== Purpose

This document describes the openEHR Base Types, whose semantics are used by all other openEHR specifications.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Research groups using openEHR, ISO 13606, archetypes and related technologies;
* The open source healthcare community;
* Solution vendors.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_base_types}.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira}/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Previous Versions

This specification is based on the types orginally defined in the {openehr_rm_103_support}[openEHR Support Information Model from Release 1.0.3 of the Reference Model]. Some changes have been made as follows.

=== Interval types

The additional types `Point_interval` and `Proper_interval` have been added, to support the common need for a point value and a proper interval to be specified as substitutable types. The types `Multiplicity_interval` and `Cardinality` have been added, from the {openehr_am_aom2}[AOM2 specification].

=== Date/Time types

The date/time types have been adjusted to provide a fully coherent model that accounts for 'native' types and the ISO 8601-based types, whose representation is a `String`. This involved the addition of notional types `IDate`, `ITime` etc, which define pure interfaces to both native and ISO 8601 date/time types.

In the original Support IM specification, only the ISO 8601 types were defined. The addition of so-called native types `Date`, `Time`, `Date_time` and `Duration` enables these types to be used in other specifications as standing for the native system types, for example in the {openehr_am_aom2}[AOM2 specification].