= Preface

== Purpose

This document describes the syntax of the Object Data Instance Notation (ODIN), previously known as the 'dADL' syntax from the openEHR ADL specifications. It is intended for software developers, technically-oriented domain specialists and subject matter experts (SMEs). ODIN is designed as a human-readable and computer-processible data representation syntax, and can be hand-edited using a normal text editor.

== Nomenclature

In this document, the term 'attribute' denotes any stored property of a type defined in an object model, including primitive attributes and any kind of relationship such as an association or aggregation.  Where XML is mentioned, XML 'attributes' are always referred to explicitly as 'XML attributes'.

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_odin}[{openehr_odin}].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list].

Issues may be raised on the {openehr_jira_prs_lang}[specifications Problem Report tracker].

To see changes made due to previously reported issues, see the {openehr_jira_crs_lang}[{component} component Change Request tracker].


