= Preface

== Purpose

This document describes the syntax of the Object Data Instance Notation (ODIN), previously known
as the 'dADL' syntax from the openEHR ADL specifications. It is intended for software developers,
technically-oriented domain specialists and subject matter experts (SMEs). ODIN is designed as a
human-readable and computer-processible data representation syntax, and can be hand-edited using a
normal text editor.

== Nomenclature

In this document, the term 'attribute' denotes any stored property of a type defined in an object
model, including primitive attributes and any kind of relationship such as an association or aggregation.
Where XML is mentioned, XML 'attributes' are always referred to explicitly as 'XML
attributes'.

== Status

This specification is in the Stable state. The development version of this document can be found at http://www.openehr.org/releases/BASE/dev/odin.html.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].


