=== BMM_ENTITY Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_ENTITY (abstract)_*

h|*Description*
2+a|Abstract parent of type and class meta-types.

h|*Inherit*
2+|`BMM_DEFINITIONS`

h|*Constants*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*Entity_metatype_simple*: `String{nbsp}={nbsp}"simple_entity"`
a|Category of a simple entity, other than enumerated types.

h|*1..1*
|*Entity_metatype_enumeration*: `String{nbsp}={nbsp}"enumeration_entity"`
a|Category of any enumeration entity.

h|*1..1*
|*Entity_metatype_generic*: `String{nbsp}={nbsp}"generic_entity"`
a|Category of any generic entity that is not a container entity.

h|*1..1*
|*Entity_metatype_parameter*: `String{nbsp}={nbsp}"generic_parameter_entity"`
a|Category of a formal generic parameter entity.

h|*1..1*
|*Entity_metatype_container*: `String{nbsp}={nbsp}"container_entity"`
a|Category of any container entity.

h|*1..1*
|*Entity_category_modifier_abstract*: `String{nbsp}={nbsp}"abstract"`
a|Category modifier indicating an entity is formally defined as abstract, i.e. not-directly instantiable within a BMM model.

h|*1..1*
|*Entity_category_modifier_primitive*: `String{nbsp}={nbsp}"primitive"`
a|Category modifier indicating that an entity is considered to be primitive within the type system of a given BMM model. Has no semantic consequences within the BMM.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(abstract)
|*entity_category* (): `String`
a|Generate a category code-string to use in visualisation, that indicates:

* _entity meta-type_: simple &#124; enumerated &#124; generic &#124; generic_effective &#124; parameter
* _abstract modifier_ - abstract status
* _primitive modifier_ primitive status

The code is structured as:

----
entity_metatype [ '-' abstract_modifier ] [ '-' primitive_modifier ]
----

h|(abstract)
|*entity_metatype* (): `String`
a|Meta-type of entity, which classifies it according to the kind of formal entity it represents from the following:

* simple (non-generic)
* generic
* enumeration
* type parameter
* container type

These meta-types don't exactly match the `BMM_*` types defined in the model, but are useful for displaying models visually.

h|(abstract)
|*is_abstract* (): `Boolean`
a|If true, indicates an abstract class in a BMM model, or a type based on an abstract class, i.e. a type that cannot be directly instantiated.

h|(abstract)
|*is_primitive* (): `Boolean`
a|If True, indicates that the entity in a BMM model is considered to relate to a primitive type set, i.e. be a primitive type, or be a definer of one.
|===
