=== BMM_SCHEMA Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_SCHEMA (abstract)_*

h|*Description*
2+a|Parent of pesistable forms of `BMM_MODEL`. Defines the abstract interface and some common implementation elements for descendants, which provide concrete persistence formats.

h|*Inherit*
2+|`P_BMM_PACKAGE_CONTAINER`, `BMM_MODEL_METADATA`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*bmm_version*: `String`
a|Version of BMM model, enabling schema evolution reasoning. Persisted attribute.

h|*0..1*
|*primitive_types*: `List<P_BMM_CLASS>`
a|Primitive type definitions. Persisted attribute.

h|*0..1*
|*class_definitions*: `List<P_BMM_CLASS>`
a|Class definitions. Persisted attribute.

h|*0..1*
|*includes*: `Hash<String,BMM_INCLUDE_SPEC>`
a|Inclusion list, in the form of a hash of individual include specifications, each of which at least specifies the id of another schema, and may specify a namespace via which types from the included schemas are known in this schema.
Persisted attribute.

h|*0..1*
|*bmm_schema*: `BMM_MODEL`
a|Generated by create_bmm_schema from persisted elements.

h|*1..1*
|*state*: `BMM_SCHEMA_STATE`
a|Current processing state.

h|*0..1*
|*model_name*: `String`
a|Name of this model, if this schema is a model root point. Not set for sub-schemas that are not considered models on their own.

h|*1..1*
|*schema_name*: `String`
a|Name of model expressed in schema; a 'schema' usually contains all of the packages of one 'model' of a publisher. A publisher with more than one model can have multiple schemas.

h|*1..1*
|*schema_revision*: `String`
a|Revision of schema.

h|*1..1*
|*schema_lifecycle_state*: `String`
a|Schema development lifecycle state.

h|*1..1*
|*schema_author*: `String`
a|Primary author of schema.

h|*1..1*
|*schema_description*: `String`
a|Description of schema.

h|*0..1*
|*schema_contributors*: `List<String>`
a|Contributing authors of schema.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(abstract)
|*validate_created* +
*_Pre_state_*: `state = State_created` +
*_Post_state_*: `passed implies state = State_validated_created`
a|Do some basic validation post initial creation

* check that package structure is regular:
** only top-level packages can have qualified names
** no top-level package name can be a direct parent or child of another (child package must be declared under the parent)
* check that all classes are mentioned in the package structure
* check that all models refer to valid packages

h|(abstract)
|*load_finalise* +
*_Pre_state_*: `state = State_validated_created` +
*_Post_state_*: `state = State_includes_processed or state = State_includes_pending`
a|Finalisation work:

* convert packages to canonical form, i.e. full hierarchy with no packages with names like aa.bb.cc
* set up include processing list

h|(abstract)
|*merge* ( +
other: `BMM_SCHEMA[1]` +
) +
*_Pre_state_*: `state = State_includes_pending` +
*_Pre_other_valid_*: `includes_to_process.has (included_schema.schema_id)`
a|Merge in class and package definitions from `_other_`, except where the current schema already has a definition for the given type or package.

h|(abstract)
|*validate*
a|Main validation prior to generation of `_bmm_model_`.

h|(abstract)
|*create_bmm_model* +
*_Pre_state_*: `state = P_BMM_PACKAGE_STATE.State_includes_processed`
a|Populate `_bmm_model_` from schema.

h|
|*read_to_validate* (): `Boolean` +
*_Post_state_*: `state = State_includes_processed`
a|

h|
|*schema_id* (): `String`
a|Identifier of this schema, used for stating inclusions and identifying files. Formed as:

`_rm_publisher_ '_' _schema_name_ '_' _rm_release_`

E.g. `'openehr_rm_ehr_1.0.4'`.
|===
