=== BMM_GENERIC_TYPE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_GENERIC_TYPE*

h|*Description*
2+a|Type reference based on a generic class, e.g. `HashTable <List <Packet>, String>`.

h|*Inherit*
2+|`BMM_DEFINED_TYPE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*generic_parameters*: `List<BMM_UNITARY_TYPE>`
a|Generic parameters of the `_root_type_` in this type specifier. The order must match the order of the owning class's formal generic parameter declarations.

h|*1..1 +
(redefined)*
|*base_class*: `BMM_GENERIC_CLASS`
a|The target type; this converts to the first parameter in `_generic_parameters_` in `BMM_GENERIC_TYPE`.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*type_name* (): `String`
a|Return the full name of the type including generic parameters, e.g. `DV_INTERVAL<T>`, `TABLE<List<THING>,String>`.

h|(redefined)
|*type_signature* (): `String`
a|Signature form of the type, which for generics includes generic parameter constrainer types E.g. `Interval<T:Ordered>`.

h|(effected)
|*is_abstract* (): `Boolean`
a|True if `_base_class.is_abstract_` or if any (non-open) parameter type is abstract.

h|(effected)
|*flattened_type_list* (): `List<String>`
a|Result is `_base_class.name_` followed by names of all generic parameter type names, which may be open or closed.

h|(effected)
|*subtypes* (): `List<String>`
a|Result is the permutation of the base class type and type substitutions of all generic parameters.

h|(effected)
|*has_subtypes* (): `Boolean`
a|True if `_base_class.has_descendants_` or any generic parameter type `_type_substitutions_` is True.

h|
|*is_partially_closed* (): `Boolean`
a|Returns True if there is any substituted generic parameter.

h|(effected)
|*effective_base_class* (): `BMM_GENERIC_CLASS`
a|Effective underlying class for this type, abstracting away any container type.
|===
