=== BMM_SCHEMA_DESCRIPTOR Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_SCHEMA_DESCRIPTOR (abstract)_*

h|*Description*
2+a|Descriptor for a BMM schema. Contains a meta-data table of attributes obtained from a mini-ODIN parse of the  schema file.

h|*Inherit*
2+|`BMM_DEFINITIONS`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*bmm_schema*: `BMM_SCHEMA`
a|Persistent form of model.

h|*0..1*
|*bmm_model*: `BMM_MODEL`
a|Computable form of model.

h|*1..1*
|*schema_id*: `String`
a|Schema id, formed from:

* `meta_data.item(Metadata_model_publisher)` '-' `meta_data.item(metadata_schema_name)` '-' `meta_data.item(Metadata_model_release)`

e.g. `openehr_rm_1.0.3`, `openehr_test_1.0.1`, `iso_13606_1_2008_2.1.2`.

h|*1..1*
|*meta_data*: `Hash<String, String>`
a|Table of `{key, value}` pairs of schema meta-data, keys are string values corresponding to values in `P_BMM_SCHEMA_METADATA_KEY`.

h|*0..1*
|*includes*: `List<String>`
a|Identifiers of schemas included by this schema.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_top_level* (): `Boolean`
a|True if this is a top-level schema, i.e. not included by some other schema.

h|
|*is_bmm_compatible* (): `Boolean`
a|True if the BMM version found in the schema (or assumed, if none) is compatible with that in this software.

h|
|*load*
a|Load schema into in-memory form, i.e. a `P_BMM_SCHEMA` instance, if structurally valid. If successful, `_p_schema_` will be set.

h|
|*validate_merged*
a|Validate loaded schema and report errors.

h|
|*validate_includes* ( +
all_schemas_list: `List<String>[0..1]` +
)
a|Validate includes list for this schema, to see if each mentioned schema exists in `_all_schemas_` list.

h|
|*create_model*
a|Create `schema`, i.e. the `BMM_MODEL` from one `P_BMM_SCHEMA` schema.
|===
