=== BMM_GENERIC_CLASS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_GENERIC_CLASS*

h|*Description*
2+a|Definition of a generic class in an object model.

h|*Inherit*
2+|`BMM_CLASS`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*generic_parameters*: `Hash<String,BMM_PARAMETER_TYPE>`
a|List of generic parameter definitions, keyed by name of generic parameter; these are defined either directly on this class or by the addition of an ancestor class which is generic.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(redefined)
|*suppliers* (): `List<String>`
a|Add suppliers from generic parameters.

h|(effected)
|*entity_metatype* (): `String`
a|Meta-type of `BMM_GENERIC_CLASS`, which is `Entity_metatype_generic`.

h|(effected)
|*type* (): `BMM_GENERIC_TYPE`
a|Generate a fully open `BMM_GENERIC_TYPE` instance that corresponds to this class definition

h|
|*generic_parameter_conformance_type* ( +
a_name: `String[1]` +
): `String`
a|For a generic class, type to which generic parameter `a_name` conforms e.g. if this class is `Interval <T:Comparable>` then the Result will be the single type `Comparable`. For an unconstrained type `T`, the Result will be `Any`.
|===
