=== BMM_TYPE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_TYPE (abstract)_*

h|*Description*
2+a|Abstract idea of specifying a type in some context. This is not the same as 'defining' a class. A type specification is essentially a reference of some kind, that defines the type of an attribute, or function result or argument. It may include generic parameters that might or might not be bound. See subtypes.

h|*Inherit*
2+|`BMM_ENTITY`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(abstract)
|*effective_base_class* (): `BMM_CLASS`
a|Effective underlying class for this type, abstracting away any container type.

h|(abstract)
|*type_name* (): `String`
a|Formal string form of the type as per UML.

h|(abstract)
|*has_subtypes* (): `Boolean`
a|Determine if there are any type substitutions.

h|(abstract)
|*subtypes* (): `List<String>`
a|List of type substitutions if any available for this type within the current BMM model.

h|(abstract)
|*flattened_type_list* (): `List<String>`
a|Completely flattened list of type names, flattening out all generic parameters.

h|
|*type_signature* (): `String`
a|Signature form of the type, which for generics includes generic parameter constrainer types E.g. `Interval<T:Ordered>`.

Generally useful for display purposes.

h|(effected)
|*is_primitive* (): `Boolean`
a|True if `_base_class.is_primitive_`.

h|(effected)
|*entity_metatype* (): `String`
a|Meta-type of type is by default assumed to be the meta-type of its `_base_class_`.
|===
