=== BMM_SCHEMA Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__BMM_SCHEMA (abstract)__*

h|*Description*
2+a|Parent of pesistable forms of `BMM_MODEL`. Defines the abstract interface and some common implementation elements for descendants, which provide concrete persistence formats.

h|*Inherit*
2+|`link:/releases/BASE/{base_release}/bmm_persistence.html#_p_bmm_package_container_class[P_BMM_PACKAGE_CONTAINER^]`, `<<_bmm_model_metadata_class,BMM_MODEL_METADATA>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*bmm_version*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Version of BMM model, enabling schema evolution reasoning. Persisted attribute.

h|*0..1*
|*primitive_types*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/bmm_persistence.html#_p_bmm_class_class[P_BMM_CLASS^]>`
a|Primitive type definitions. Persisted attribute.

h|*0..1*
|*class_definitions*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/bmm_persistence.html#_p_bmm_class_class[P_BMM_CLASS^]>`
a|Class definitions. Persisted attribute.

h|*0..1*
|*includes*: `link:/releases/BASE/{base_release}/foundation_types.html#_hash_class[Hash^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^],link:/releases/BASE/{base_release}/bmm_persistence.html#_bmm_include_spec_class[BMM_INCLUDE_SPEC^]>`
a|Inclusion list, in the form of a hash of individual include specifications, each of which at least specifies the id of another schema, and may specify a namespace via which types from the included schemas are known in this schema.
Persisted attribute.

h|*0..1*
|*bmm_schema*: `<<_bmm_model_class,BMM_MODEL>>`
a|Generated by create_bmm_schema from persisted elements.

h|*1..1*
|*state*: `link:/releases/BASE/{base_release}/bmm_persistence.html#_bmm_schema_state_enumeration[BMM_SCHEMA_STATE^]`
a|Current processing state.

h|*0..1*
|*model_name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Name of this model, if this schema is a model root point. Not set for sub-schemas that are not considered models on their own.

h|*1..1*
|*schema_name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Name of model expressed in schema; a 'schema' usually contains all of the packages of one 'model' of a publisher. A publisher with more than one model can have multiple schemas.

h|*1..1*
|*schema_revision*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Revision of schema.

h|*1..1*
|*schema_lifecycle_state*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Schema development lifecycle state.

h|*1..1*
|*schema_author*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Primary author of schema.

h|*1..1*
|*schema_description*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Description of schema.

h|*0..1*
|*schema_contributors*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]>`
a|Contributing authors of schema.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(abstract)*
|*validate_created* +
 +
__Pre_state__: `state = State_created` +
__Post_state__: `passed implies state = State_validated_created`
a|Do some basic validation post initial creation

* check that package structure is regular:
** only top-level packages can have qualified names
** no top-level package name can be a direct parent or child of another (child package must be declared under the parent)
* check that all classes are mentioned in the package structure
* check that all models refer to valid packages

h|*0..1 +
(abstract)*
|*load_finalise* +
 +
__Pre_state__: `state = State_validated_created` +
__Post_state__: `state = State_includes_processed or state = State_includes_pending`
a|Finalisation work:

* convert packages to canonical form, i.e. full hierarchy with no packages with names like aa.bb.cc
* set up include processing list

h|*0..1 +
(abstract)*
|*merge* ( +
other: `<<_bmm_schema_class,BMM_SCHEMA>>[1]` +
) +
 +
__Pre_state__: `state = State_includes_pending` +
__Pre_other_valid__: `includes_to_process.has (included_schema.schema_id)`
a|Merge in class and package definitions from `_other_`, except where the current schema already has a definition for the given type or package.

h|*0..1 +
(abstract)*
|*validate*
a|Main validation prior to generation of `_bmm_model_`.

h|*0..1 +
(abstract)*
|*create_bmm_model* +
 +
__Pre_state__: `state = P_BMM_PACKAGE_STATE.State_includes_processed`
a|Populate `_bmm_model_` from schema.

h|*1..1*
|*read_to_validate* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]` +
 +
__Post_state__: `state = State_includes_processed`
a|

h|*1..1*
|*schema_id* (): `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Identifier of this schema, used for stating inclusions and identifying files. Formed as:

`_rm_publisher_ '_' _schema_name_ '_' _rm_release_`

E.g. `'openehr_rm_ehr_1.0.4'`.
|===
