=== BMM_CONTAINER_TYPE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_CONTAINER_TYPE*

h|*Description*
2+a|Type that specifies linear containers with a generic parameter corresponding to the type of contained item, and whose container type is a generic type such as `List<T>`, `Set<T>` etc.

h|*Inherit*
2+|`BMM_TYPE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*container_class*: `BMM_GENERIC_CLASS`
a|The type of the container. This converts to the `_root_type_` in `BMM_GENERIC_TYPE`.

h|*1..1*
|*base_type*: `BMM_UNITARY_TYPE`
a|The target type; this converts to the first parameter in `_generic_parameters_` in `BMM_GENERIC_TYPE`.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*type_name* (): `String`
a|Return full type name, e.g. `List<ELEMENT>`.

h|(effected)
|*effective_base_class* (): `BMM_CLASS` +
*_Post_validity_*: `Result = base_type.base_class`
a|Result is `_base_class_` of `_base_type_`.

h|(effected)
|*is_abstract* (): `Boolean`
a|True if `_base_type.is_abstract_` or `_container_type.is_abstract_`.

h|(effected)
|*entity_metatype* (): `String`
a|Meta-type of container type is `Classifier_metatype_container`.

h|(effected)
|*flattened_type_list* (): `List<String>`
a|Completely flattened list of type names, flattening out all generic parameters.

h|(effected)
|*subtypes* (): `List<String>`
a|Result is all permutations of current container type and its descendants with the current `_base_type_` and its descendants.

h|(effected)
|*has_subtypes* (): `Boolean`
a|Determine if there are any type substitutions.
|===
