=== BMM_MODEL Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_MODEL*

h|*Description*
2+a|Definition of the root of a BMM model (along with what is inherited from `BMM_SCHEMA_CORE`).

h|*Inherit*
2+|`BMM_PACKAGE_CONTAINER`, `BMM_MODEL_METADATA`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*class_definitions*: `Hash<String,BMM_CLASS>`
a|All classes in this schema, keyed by type name.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*model_id* (): `String`
a|Identifier of this model, lower-case, formed from:

`rm_publisher '_' model_name '_' rm_release`

E.g. `'openehr_ehr_1.0.4'`.

h|
|*class_definition* ( +
a_name: `String[1]` +
): `BMM_CLASS`
a|Retrieve the class definition corresponding to `_a_type_name_` (which may contain a generic part).

h|
|*type_definition* (): `BMM_CLASS`
a|Retrieve the class definition corresponding to `_a_type_name_`. If it contains a generic part, this will be removed if it is a fully open generic name, otherwise it will remain intact, i.e. if it is an effective generic name that identifies a `BMM_GENERIC_CLASS_EFFECTIVE`.

h|
|*has_class_definition* ( +
a_class_name: `String[1]` +
): `Boolean`
a|True if `_a_class_name_` has a class definition in the model.

h|
|*has_type_definition* ( +
a_type_name: `String[1]` +
): `Boolean`
a|True if `_a_type_name_` is already concretely known in the system, including if it is generic, which may be open, partially open or closed.

h|
|*enumeration_definition* ( +
a_name: `String[1]` +
): `BMM_ENUMERATION`
a|Retrieve the enumeration definition corresponding to `_a_type_name_`.

h|
|*primitive_types* (): `List<String>`
a|List of keys in `_class_definitions_` of items marked as primitive types.

h|
|*enumeration_types* (): `List<String>`
a|List of keys in `_class_definitions_` of items that are enumeration types.

h|
|*property_definition* (): `BMM_PROPERTY`
a|Retrieve the property definition for `_a_prop_name_` in flattened class corresponding to `_a_type_name_`.

h|
|*ms_conformant_property_type* ( +
a_bmm_type_name: `String[1]`, +
a_bmm_property_name: `String[1]`, +
a_ms_property_name: `String[1]` +
): `Boolean`
a|True if `_a_ms_property_type_` is a valid 'MS' dynamic type for `_a_property_` in BMM type `_a_bmm_type_name_`. 'MS' conformance means 'model-semantic' conformance, which abstracts away container types like `List<>`, `Set<>` etc and compares the dynamic type with the relation target type in the UML sense, i.e. regardless of whether there is single or multiple containment.

h|
|*property_definition_at_path* (): `BMM_PROPERTY`
a|Retrieve the property definition for `_a_property_path_` in flattened class corresponding to `_a_type_name_`.

h|
|*class_definition_at_path* ( +
a_type_name: `String[1]`, +
a_prop_path: `String[1]` +
): `BMM_CLASS`
a|Retrieve the class definition for the class that owns the terminal attribute in `a_prop_path` in flattened class corresponding to `a_type_name`.

h|
|*all_ancestor_classes* ( +
a_class: `String[1]` +
): `List<String>`
a|Return all ancestor types of `_a_class_name_` up to root class (usually `Any`, `Object` or something similar). Does  not include current class. Returns empty list if none.

h|
|*is_descendant_of* ( +
a_class_name: `String[1]`, +
a_parent_class_name: `String[1]` +
): `Boolean`
a|True if `_a_class_name_` is a descendant in the model of `_a_parent_class_name_`.

h|
|*type_conforms_to* ( +
a_desc_type: `String[1]`, +
an_anc_type: `String[1]` +
): `Boolean`
a|Check conformance of `_a_desc_type_` to `_an_anc_type_`; the types may be generic, and may contain open generic parameters like 'T' etc. These are replaced with their appropriate constrainer types, or Any during the conformance testing process.

Conformance is found if:

* [base class test] types are non-generic, and either type names are identical, or else `_a_desc_type_` has `_an_anc_type_` in its ancestors;
* both types are generic and pass base class test; number of generic params matches, and each generic parameter type, after 'open parameter' substitution, recursively passes; `_type_name_conforms_to_` test
* descendant type is generic and ancestor type is not, and they pass base classes test.

h|
|*any_class_definition* (): `BMM_SIMPLE_CLASS`
a|`BMM_CLASS` instance for the `Any` class. This may be defined in the BMM schema, but if not, a default `Any` class will be generated.

h|
|*any_type_definition* (): `BMM_SIMPLE_TYPE`
a|
|===
