=== BMM_MODEL Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_MODEL*

h|*Description*
2+a|Model of a BMM schema (along with what is inherited from BMM_SCHEMA_CORE).

h|*Inherit*
2+|`BMM_SCHEMA_CORE`, `BMM_PACKAGE_CONTAINER`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*class_definitions*: `Hash<String,BMM_CLASS>`
a|All classes in this schema.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*primitive_types* (): `List<String>`
a|List of keys in `class_definitions' of items marked as primitive types, as defined in input schema.

h|
|*enumeration_types* (): `List<String>`
a|List of keys in `class_definitions' of items that are enumeration types, as defined in input schema.

h|
|*class_definition* ( +
a_name: `String[1]` +
): `BMM_CLASS`
a|Retrieve the class definition corresponding to `a_type_name' (which may contain a generic part).

h|
|*enumeration_definition* ( +
a_name: `String[1]` +
): `BMM_ENUMERATION`
a|Retrieve the enumeration definition corresponding to `a_type_name'.

h|
|*property_definition* (): `BMM_PROPERTY`
a|Retrieve the property definition for `a_prop_name' in flattened class corresponding to `a_type_name'.

h|
|*ms_conformant_property_type* ( +
a_bmm_type_name: `String[1]`, +
a_bmm_property_name: `String[1]`, +
a_ms_property_name: `String[1]` +
): `Boolean`
a|True if `a_ms_property_type' is a valid 'MS' dynamic type for `a_property' in BMM type `a_bmm_type_name'. 'MS' conformance means 'model-semantic' conformance, which abstracts away container types like List<>, Set<> etc and compares the dynamic type with the relation target type in the UML sense, i.e. regardless of whether there is single or multiple containment.

h|
|*property_definition_at_path* (): `BMM_PROPERTY`
a|Retrieve the property definition for `a_property_path' in flattened class corresponding to `a_type_name'.

h|
|*all_ancestor_classes* ( +
a_class: `String[1]` +
): `List<String>`
a|Return all ancestor types of `a_class_name' up to root class (usually 'ANY', 'Object' or something similar). Does  not include current class. Returns empty list if none.

h|
|*type_conforms_to* ( +
a_desc_type, +
an_anc_type +
): `Boolean`
a|Check conformance of `a_desc_type' to `an_anc_type'; the types may be generic, and may contain open generic parameters like 'T' etc. These are replaced with their apporpriate constrainer types, or Any during the conformance testing process.

Conformance is found if:

* [base class test] types are non-generic, and either type names are identical, or else `a_desc_type' has `an_anc_type' in its ancestors
* both types are generic and pass base class test; number of generic params matches, and each generic parameter type, after 'open parameter' substitution, recursively passes `type_name_conforms_to' test
* descendant type is generic and ancestor type is not, and they pass base classes test
|===
