=== BMM_MODEL_ACCESS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_MODEL_ACCESS*

h|*Description*
2+a|Access to BMM models that have been loaded and validated from one or more schema sets.

h|*Inherit*
2+|`BMM_DEFINITIONS`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*schema_directories*: `List<String>`
a|List of directories where all the schemas loaded here are found.

h|*0..1*
|*all_schemas*: `Hash<String,BMM_SCHEMA_DESCRIPTOR>`
a|All schemas found and loaded from `_schema_directory_`. Keyed by `_schema_id_`.

h|*0..1*
|*bmm_models*: `Hash<String,BMM_MODEL>`
a|Top-level (root) schemas in use. Table is keyed by `_model_id_`.

h|*0..1*
|*matching_bmm_models*: `Hash<String,BMM_MODEL>`
a|`BMM_MODELs` keyed by `_model_id()_` and any shorter form used in calls to
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*initialise_with_load_list* ( +
a_schema_dirs: `List<String>[1]`, +
a_schema_load_list: `List<String>[0..1]` +
)
a|Initialise with a specific schema load list, usually a sub-set of schemas that will be found in a specified directories `_a_schema_dirs_`.

h|
|*initialise_all* ( +
a_schema_dirs: `List<String>[1]` +
)
a|Load all schemas found in a specified directories `_a_schema_dirs_`.

h|
|*reload_schemas*
a|Reload BMM schemas.

h|
|*bmm_model* ( +
a_model_key: `String[1]` +
): `BMM_MODEL`
a|Return ref model containing the model key which is a `_model_id_` or any shorter form e.g. model id minus the version. If a shorter key is used, the `BMM_MODEL` with the highest version will be selected.

h|
|*has_bmm_model* ( +
a_model_key: `String[1]` +
): `Boolean`
a|True if a model for a `_model_key_` is available. A model key is a `_model_id_` or any shorter form e.g. model id minus the version. If a shorter key is used, the Result s True if a `BMM_MODEL` with any version exists.
|===
