=== BMM_SCHEMA_DESCRIPTOR Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__BMM_SCHEMA_DESCRIPTOR (abstract)__*

h|*Description*
2+a|Descriptor for a BMM schema. Contains a meta-data table of attributes obtained from a mini-ODIN parse of the  schema file.

h|*Inherit*
2+|`<<_bmm_definitions_class,BMM_DEFINITIONS>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*bmm_schema*: `<<_bmm_schema_class,BMM_SCHEMA>>`
a|Persistent form of model.

h|*0..1*
|*bmm_model*: `<<_bmm_model_class,BMM_MODEL>>`
a|Computable form of model.

h|*1..1*
|*schema_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Schema id, formed from:

* `meta_data.item(Metadata_model_publisher)` '-' `meta_data.item(metadata_schema_name)` '-' `meta_data.item(Metadata_model_release)`

e.g. `openehr_rm_1.0.3`, `openehr_test_1.0.1`, `iso_13606_1_2008_2.1.2`.

h|*1..1*
|*meta_data*: `link:/releases/BASE/{base_release}/foundation_types.html#_hash_class[Hash^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^], link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]>`
a|Table of `{key, value}` pairs of schema meta-data, keys are string values corresponding to values in `P_BMM_SCHEMA_METADATA_KEY`.

h|*0..1*
|*includes*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]>`
a|Identifiers of schemas included by this schema.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*is_top_level* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if this is a top-level schema, i.e. not included by some other schema.

h|*1..1*
|*is_bmm_compatible* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if the BMM version found in the schema (or assumed, if none) is compatible with that in this software.

h|*0..1*
|*load*
a|Load schema into in-memory form, i.e. a `P_BMM_SCHEMA` instance, if structurally valid. If successful, `_p_schema_` will be set.

h|*0..1*
|*validate_merged*
a|Validate loaded schema and report errors.

h|*0..1*
|*validate_includes* ( +
all_schemas_list: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]>[0..1]` +
)
a|Validate includes list for this schema, to see if each mentioned schema exists in `_all_schemas_` list.

h|*0..1*
|*create_model*
a|Create `schema`, i.e. the `BMM_MODEL` from one `P_BMM_SCHEMA` schema.
|===
