=== BMM_PARAMETER_TYPE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_PARAMETER_TYPE*

h|*Description*
2+a|Definition of a generic parameter in a class definition of a generic type.

h|*Inherit*
2+|`BMM_UNITARY_TYPE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*name*: `String`
a|Name of the parameter, e.g. 'T' etc. The name is limited to 1 character and upper-case.

h|*0..1*
|*type_constraint*: `BMM_DEFINED_TYPE`
a|Optional conformance constraint that must be another valid class name.

h|*0..1*
|*inheritance_precursor*: `BMM_PARAMETER_TYPE`
a|If set, is the corresponding generic parameter definition in an ancestor class.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*flattened_conforms_to_type* (): `String`
a|Result is either `_conforms_to_type_` or `_inheritance_precursor.flattened_conforms_to_type_`.

h|
|*effective_conforms_to_type* (): `BMM_CLASS`
a|Generate ultimate conformance type, which is either `_flattened_conforms_to_type_` or if not set, `Any`.

h|(redefined)
|*type_signature* (): `String`
a|Signature form of the open type, including constrainer type if there is one, e.g. `T:Ordered`.

h|(effected)
|*is_primitive* (): `Boolean`
a|Result = `False` - generic parameters are understood by definition to be non-primitive.

h|(effected)
|*is_abstract* (): `Boolean`
a|Result = `False` - generic parameters are understood by definition to be non-abstract.

h|(effected)
|*entity_metatype* (): `String`
a|Meta-type of a container type is `Entity_metatype_generic_parameter`.

h|(effected)
|*effective_base_class* (): `BMM_CLASS`
a|The effective conformance type of this parameter, or the 'Any' class if none.

h|(effected)
|*has_subtypes* (): `Boolean`
a|True if `_effective_conforms_to_type.base_class.has_descendants_`.

h|(effected)
|*subtypes* (): `List<String>`
a|Result is `_effective_conforms_to_type.base_class.all_descendants_` .

h|(effected)
|*type_name* (): `String`
a|Result is `_name_`.

h|(effected)
|*flattened_type_list* (): `List<String>`
a|Result is either `_flattened_conforms_to_type.flattened_type_list_` or the `Any` type.

h|*Invariants*
2+a|*_Inv_generic_name_*: `name.count = 1 and name.is_upper`
|===
