=== BMM_ENUMERATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_ENUMERATION*

h|*Description*
2+a|Definition of an enumeration type. In the BMM system, an 'enumeration' type is understood as an underlying basic type and a set of named constants of that type. It is designed so that the default type is Integer, and the default constants are numbered 0, 1, ... Optional model elements can be specified to override the values and / or the type.

h|*Inherit*
2+|`BMM_SIMPLE_CLASS`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*item_names*: `List<String>`
a|The list of names of the enumeration. If no values are supplied, the integer values 0, 1, 2, ... are assumed.

h|*0..1*
|*item_values*: `List<T>`
a|Optional list of specific values. Must be 1:1 with `_item_names_` list.

h|*1..1*
|*underlying_type_name*: `String`
a|Name of type any concrete `BMM_ENUMERATION_*` sub-type is based on, i.e. the name of type bound to 'T' in a declared use of this type.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*entity_metatype* (): `String`
a|Meta-type of `BMM_ENUMERATION`, which is `Entity_metatype_enumeration`.

h|
|*name_map* (): `Hash<String,String>`
a|Map of `_item_values_` (stringified) to `_item_names_`.
|===
