=== Cardinality Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Cardinality*

h|*Description*
2+a|Express constraints on the cardinality of container objects which are the values of multiply-valued attributes, including uniqueness and ordering, providing the means to state that a container acts like a logical list, set or bag.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*interval*: `Multiplicity_interval`
a|The interval of this cardinality.

h|*1..1*
|*is_ordered*: `Boolean`
a|True if the members of the container attribute to which this cardinality refers are ordered.

h|*1..1*
|*is_unique*: `Boolean`
a|True if the members of the container attribute to which this cardinality refers are unique.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_bag* (): `Boolean`
a|True if the semantics of this cardinality represent a bag, i.e. unordered, non-unique membership.

h|
|*is_list* (): `Boolean`
a|True if the semantics of this cardinality represent a list, i.e. ordered, non-unique membership.

h|
|*is_set* (): `Boolean`
a|True if the semantics of this cardinality represent a set, i.e. unordered, unique membership.
|===
