=== Container<T> Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_Container<T> (abstract)_*

h|*Description*
2+a|Abstract ancestor of container types whose items are addressable in some way.

h|*Inherit*
2+|`Any`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(abstract)*
|*has* ( +
v: `T[1]` +
): `Boolean`
a|Test for membership of a value.

h|*1..1 +
(abstract)*
|*count* (): `Integer`
a|Number of items in container.

h|*1..1 +
(abstract)*
|*is_empty* (): `Boolean`
a|True if container is empty.

h|*1..1*
|*there_exists* _alias_ "there exists", "∃" ( +
test: `Operation[1]` +
): `Boolean`
a|Existential quantifier applied to container, taking one agent argument `_test_` whose signature is `(v:T): Boolean`.

h|*1..1*
|*for_all* _alias_ "for all", "∀" ( +
test: `Operation[1]` +
): `Boolean`
a|Universal quantifier applied to container, taking one agent argument `_test_` whose signature is `(v:T): Boolean`.

h|*0..1*
|*matching* ( +
test: `Operation[1]` +
): `List<T>`
a|Return a List all items matching the predicate function `_test_` which has signature `(v:T): Boolean`. If no matches, an empty List is returned.

h|*0..1*
|*select* ( +
test: `Operation[1]` +
): `T`
a|Return first item matching the predicate function `_test_` which has signature `(v:T): Boolean`, or Void if no match.
|===
