=== Date_time Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*Date_time*

h|*Description*
2+a|Represents an absolute point in time, specified to the second.

Note that this class includes 2 deviations from ISO 8601:2004:

* for partial date/times, any part of the date/time up to the month may be missing, not just seconds and minutes as in the standard;
* the time 24:00:00 is not allowed, since it would mean the date was really on the next day.

h|*Inherit*
2+|Temporal

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*year*: `Integer`
a|Year.

h|
|*month*: `Integer` +
*_Pre_*: not month_unknown
a|Month in year.

h|
|*day*: `Integer` +
*_Pre_*: not day_unknown
a|Day in month.

h|
|*hour*: `Integer` +
*_Pre_*: not hour_unknown
a|Hour in day.

h|
|*minute*: `Integer` +
*_Pre_*: not minute_unknown
a|Minute in hour.

h|
|*second*: `Integer` +
*_Pre_*: not second_unknown
a|Second in minute.

h|
|*fractional_second*: `Real`
a|Fractional seconds.

h|
|*has_fractional_second*: `Boolean`
a|True if the fractional_second part is signficant (i.e. even if = 0.0).

h|
|*timezone*: `Timezone`
a|Timezone; may be Void.

h|
|*as_string*: `String`
a|ISO8601 string for date/time, in format `YYYYMMDDThhmmss[,sss][Z &#124; ±hh[mm]]` or in extended format `YYYY-MM-DDThh:mm:ss[,sss][Z &#124; ±hh[mm]]` or a partial variant; see valid_iso8601_date_time() below.

h|*Invariant*
2+a|*_Day_valid_*: valid_day(year, month, day)

h|
2+a|*_Month_valid_*: valid_month (month)

h|
2+a|*_Year_valid_*: valid_year (year)

h|
2+a|*_Month_valid_*: valid_month (month)

h|
2+a|*_Day_valid_*: valid_day(year, month, day)

h|
2+a|*_Hour_valid_*: valid_hour (hour, minute, second)
|===
