=== Double Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Double*

h|*Description*
2+a|Type used to represent double-precision decimal numbers. Corresponds to a double-precision floating point value in most languages.

h|*Inherit*
2+|`Ordered_Numeric`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*floor* (): `Integer`
a|Return the greatest integer no greater than the value of this object.

h|*1..1 +
(effected)*
|*add* _alias_ "+" ( +
other: `Double[1]` +
): `Double`
a|Double-precision real number addition.

h|*1..1 +
(effected)*
|*subtract* _alias_ "-" ( +
other: `Double[1]` +
): `Double`
a|Double-precision real number subtraction.

h|*1..1 +
(effected)*
|*multiply* _alias_ "&#42;" ( +
other: `Double[1]` +
): `Double`
a|Double-precision real number multiplication.

h|*1..1 +
(effected)*
|*divide* _alias_ "/" ( +
other: `Double[1]` +
): `Double`
a|Double-precision real number division.

h|*1..1 +
(effected)*
|*exponent* _alias_ "^" ( +
other: `Double[1]` +
): `Double`
a|Double-precision real number exponentiation.

h|*1..1 +
(effected)*
|*less_than* _alias_ "<" ( +
other: `Double[1]` +
): `Boolean`
a|Returns True if current Double is less than `_other_`.

h|*1..1 +
(effected)*
|*negative* _alias_ "-" (): `Double`
a|Generate negative of current Double value.

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `Double[1]` +
): `Boolean`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|*1..1 +
(redefined)*
|*equal* _alias_ "=", "==" ( +
other: `Double[1]` +
): `Boolean`
a|Reference equality for reference types, value equality for value types.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.
|===
