=== Integer64 Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Integer64*

h|*Description*
2+a|Type representing minimal interface of built-in Integer64 type.

h|*Inherit*
2+|`Ordered_Numeric`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*add* _alias_ "+" ( +
other: `Integer[1]` +
): `Integer64`
a|Large integer addition.

h|(effected)
|*subtract* _alias_ "-" ( +
other: `Integer[1]` +
): `Integer64`
a|Large integer subtraction.

h|(effected)
|*multiply* _alias_ "&#42;" ( +
other: `Integer[1]` +
): `Integer64`
a|Large integer multiplication.

h|(effected)
|*divide* _alias_ "/" ( +
other: `Integer[1]` +
): `Double`
a|Large integer division.

h|(effected)
|*exponent* _alias_ "^" ( +
other: `Double[1]` +
): `Double`
a|Large integer exponentiation.

h|
|*modulo* _alias_ "mod", "\\" ( +
mod: `Integer[1]` +
): `Integer64`
a|Large integer modulus.

h|(effected)
|*less_than* _alias_ "<" ( +
other: `Integer64[1]` +
): `Boolean`
a|Returns True if current Integer is less than `_other_`.

h|(effected)
|*negative* _alias_ "-" (): `Integer64`
a|Generate negative of current Integer value.

h|(effected)
|*is_equal* ( +
other: `Integer64[1]` +
): `Boolean`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|(redefined)
|*equal* _alias_ "=", "==" ( +
other: `Integer64[1]` +
): `Boolean`
a|Reference equality for reference types, value equality for value types.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.
|===
