=== Interval<T> Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_Interval<T> (abstract)_*

h|*Description*
2+a|Interval abstraction, featuring upper and lower limits that may be open or closed, included or not included.
Interval of ordered items.

h|*Inherit*
2+|`Any`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*lower*: `T`
a|Lower bound.
lower bound.

h|*0..1*
|*upper*: `T`
a|Upper bound.
Upper bound.

h|*1..1*
|*lower_unbounded*: `boolean`
a|`lower` boundary open (i.e. = -infinity).
lower boundary open (i.e. = -infinity)

h|*1..1*
|*upper_unbounded*: `boolean`
a|`upper` boundary open (i.e. = +infinity).
upper boundary open (i.e. = +infinity)

h|*1..1*
|*lower_included*: `boolean`
a|`lower` boundary value included in range if not `lower_unbounded`.
lower boundary value included in range if not lower_unbounded.

h|*1..1*
|*upper_included*: `boolean`
a|`upper` boundary value included in range if not `upper_unbounded`.
upper boundary value included in range if not upper_unbounded.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(abstract)
|*has* ( +
e: `T[1]` +
): `boolean` +
 +
*_Post_result_*: `Result = (lower_unbounded or lower_included and v >= lower) or v > lower and (upper_unbounded or upper_included and v \<= upper or v < upper)`
a|True if the value `e` is properly contained in this Interval.
True if (lower_unbounded or
((lower_included and v >= lower) or
v > lower)) and
(upper_unbounded or
((upper_included and v \<= upper or v
< upper)))

h|(abstract)
|*intersects* ( +
other: `Interval[1]` +
): `Boolean`
a|True if there is any overlap between intervals represented by Current and `_other_`. True if at least one limit of other is strictly inside the limits of this interval.

h|(abstract)
|*contains* ( +
other: `Interval[1]` +
): `Boolean`
a|True if current interval properly contains `_other_`? True if all points of `_other_` are inside the current interval.

h|(effected)
|*is_equal* ( +
other: `Any[1]` +
): `Boolean`
a|True if current object's interval is semantically same as `_other_`.

h|*Invariants*
2+a|*_Lower_included_valid_*: `lower_unbounded implies not lower_included`

h|
2+a|*_Upper_included_valid_*: `upper_unbounded implies not upper_included`

h|
2+a|*_Limits_consistent_*: `(not upper_unbounded and not lower_unbounded) implies lower \<= upper`

h|
2+a|*_Limits_comparable_*: `(not upper_unbounded and not lower_unbounded) implies lower.strictly_comparable_to (upper)`
|===
