=== Interval Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*_Interval (abstract)_*

h|*Description*
2+a|Interval abstraction, featuring upper and lower limits that may be open or closed, included or not included.
Interval of ordered items.

h|*Inherit*
2+|Any

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*lower*: `T`
a|lower bound.

h|*1..1*
|*lower_unbounded*: `boolean`
a|lower boundary open (i.e. = -infinity)

h|*1..1*
|*upper_unbounded*: `boolean`
a|upper boundary open (i.e. = +infinity)

h|*1..1*
|*lower_included*: `boolean`
a|lower boundary value included in range if not lower_unbounded.

h|*1..1*
|*upper_included*: `boolean`
a|upper boundary value included in range if not upper_unbounded.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has* (e): `boolean`
a|True if (lower_unbounded or
((lower_included and v >= lower) or
v > lower)) and
(upper_unbounded or
((upper_included and v \<= upper or v
< upper)))

h|
|*intersects* (other: `Interval`): `Boolean`
a|True if there is any overlap between intervals represented by Current and `other'. True if at least one limit of other is strictly inside the limits of this interval.

h|
|*contains* (other: `Interval`): `Boolean`
a|True if current interval properly contains `other'? True if all points of `other' are inside the current interval.

h|
|*upper*: `T`
a|

h|(effected)
|*is_equal* (other: `Any`): `Boolean`
a|True if current object's interval is semantically same as `other'.

h|*Invariant*
2+a|*_Lower_included_valid_*: lower_unbounded implies not lower_included

h|
2+a|*_Upper_included_valid_*: upper_unbounded implies not upper_included

h|
2+a|*_Limits_consistent_*: (not upper_unbounded and not lower_unbounded) implies lower \<= upper

h|
2+a|*_Limits_comparable_*: (not upper_unbounded and not lower_unbounded) implies lower.strictly_comparable_to (upper)
|===
