=== ISO8601_TIMEZONE Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*ISO8601_TIMEZONE*

h|*Description*
2+a|Represents a timezone as used in ISO 8601.

h|*Inherit*
2+|TIME_DEFINITIONS

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*hour*: `Integer`
a|Hour part of timezone - in the range 00 - 13.

h|
|*minute*: `Integer`
a|Minute part of timezone. Generally 00 or 30.

h|
|*is_gmt*: `Boolean`
a|True if timezone is UTC, i.e. +0000.

h|
|*sign*: `Integer`
a|Direction of timezone expresssed as +1 or -1.

h|
|*minute_unknown*: `Integer`
a|Indicates whether minute part known.

h|
|*as_string*: `String`
a|ISO8601 timezone string, in format:

* Z &#124; ±hh[mm]

where:

* hh is “00” - “23” (0-filled to two digits)
* mm is “00” - “59” (0-filled to two digits)
* Z is a literal meaning UTC (modern replacement for GMT), i.e. timezone +0000

h|*Invariant*
2+a|*_Min_hour_valid_*: sign = -1 implies hour > 0 and hour <= Min_timezone_hour

h|
2+a|*_Max_hour_valid_*: sign = 1 implies hour > 0 and hour <= Max_timezone_hour

h|
2+a|*_Minute_valid_*: not minute_unknown implies valid_minute (minute)

h|
2+a|*_Sign_valid_*: sign = 1 or sign = -1
|===
