=== ISO8601_TIME Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*ISO8601_TIME*

h|*Description*
2+a|Represents an absolute point in time from an origin usually interpreted as meaning the start of the current day, specified to the second.

NOTE: A small deviation to the ISO 8601:2004 standard in this class is that the time 24:00:00 is not allowed, for consistency with ISO8601_DATE_TIME.

h|*Inherit*
2+|`ISO8601_TYPE`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*hour* (): `Integer`
a|Hour in day, in 24-hour time.

h|
|*minute* (): `Integer`
a|Minute in hour.

h|
|*second* (): `Integer`
a|

h|
|*fractional_second* (): `Real` +
*_Pre_*: `not second_unknown`
a|Fractional seconds.

h|
|*has_fractional_second* (): `Boolean`
a|True if the fractional_second part is signficant (i.e. even if = 0.0).

h|
|*minute_unknown* (): `Boolean`
a|Indicates whether minute is unknown. If so, the time is of the form “hh”.

h|
|*second_unknown* (): `Boolean`
a|Indicates whether second is unknown. If so and month is known, the time is of the form “hh:mm” or “hhmm”.

h|
|*is_decimal_sign_comma* (): `Boolean`
a|True if this time has a decimal part indicated by ‘,’ (comma) rather than ‘.’ (period).

h|
|*timezone* (): `ISO8601_TIMEZONE`
a|

h|
|*as_string* (): `String`
a|ISO8601 string for time, i.e. in form: hhmmss[,sss][Z&#124;hh[mm]] or the extended form: hh:mm:ss[,sss][Z&#124;hh[mm]], or a partial invariant. See valid_iso8601_time for validity.

h|(redefined)
|*is_partial* (): `Boolean`
a|True if this time is partial, i.e. if seconds or more is missing.

h|(redefined)
|*is_extended* (): `Boolean`
a|True if this time uses ‘:’ separators.

h|
|*valid_iso8601_time* (): `Boolean`
a|String is a valid ISO 8601 date, i.e. takes the form:

* hhmmss[,sss][Z &#124; hh[mm]]

or the extended form:

* hh:mm:ss[,sss][Z &#124; ±hh[mm]]

or one of the partial forms:

* hhmm or hh

or the extended form:

* hh:mm

with an additional optional timezone indicator of:
* Z or hh[mm]

Where:

* hh is “00” - “23” (0-filled to two digits)
* mm is “00” - “59” (0-filled to two digits)
* ss is “00” - “60” (0-filled to two digits)
* sss is any numeric string, representing an optional fractional second
* Z is a literal meaning UTC (modern replacement for GMT), i.e. timezone +0000
* hh[mm], i.e. +hhmm, +hh, -hhmm, -hh indicating the timezone

h|*Invariants*
2+a|*_Hour_valid_*: `valid_hour(hour, minute, second)`

h|
2+a|*_Minute_valid_*: `not minute_unknown implies valid_minute (minute)`

h|
2+a|*_Second_valid_*: `not second_unknown implies valid_second (second)`

h|
2+a|*_Fractional_second_valid_*: `has_fractional_second implies (not second_unknown and valid_fractional_second (fractional_second))`

h|
2+a|*_Partial_validity_*: `minute_unknown implies second_unknown`
|===
