=== Iso8601_date Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_date*

h|*Description*
2+a|Represents an ISO 8601 date, including partial and extended forms.

h|*Inherit*
2+|`<<_iso8601_type_class,Iso8601_type>>`, `<<_idate_class,IDate>>`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*month_unknown* (): `<<_boolean_class,Boolean>>`
a|Indicates whether month in year is unknown. If so, the date is of the form “YYYY”.

h|*1..1*
|*day_unknown* (): `<<_boolean_class,Boolean>>`
a|Indicates whether day in month is unknown. If so, and month is known, the date is of the form “YYYY-MM” or “YYYYMM”.

h|*1..1*
|*valid_iso8601_date* (): `<<_boolean_class,Boolean>>`
a|String is a valid ISO 8601 date, i.e. takes the complete form:

* YYYYMMDD or the extended form:
* YYYY-MM-DD or one of the partial forms:
* YYYYMM
* YYYY

or the equivalent extended form:

* YYYY-MM

Where:

* YYYY is the string form of any positive number in the range “0000” - “9999” (zero-filled to four digits)
* MM is “01” - “12” (zero-filled to two digits)
* DD is “01” - “31” (zero-filled to two digits)

The combinations of YYYY, MM, DD numbers must be correct with respect to the Gregorian calendar.

h|*1..1 +
(effected)*
|*is_partial* (): `<<_boolean_class,Boolean>>`
a|True if this date is partial, i.e. if days or more is missing.

h|*1..1 +
(effected)*
|*is_extended* (): `<<_boolean_class,Boolean>>`
a|True if this date uses `'-'` separators.

h|*1..1 +
(redefined)*
|*as_string* (): `<<_string_class,String>>`
a|ISO8601 string for date, in format `YYYYMMDD` or `YYYY-MM-DD`, or a partial invariant. See `_valid_iso8601_date()_` for validity.

h|*1..1*
|*as_date* (): `<<_date_class,Date>>`
a|Convert to a native `Date`.

h|*Invariants*
2+a|__Year_valid__: `valid_year (year)`

h|
2+a|__Month_valid__: `not month_unknown implies valid_month (month)`

h|
2+a|__Day_valid__: `not day_unknown implies valid_day (year, month, day)`

h|
2+a|__Partial_validity__: `month_unknown implies day_unknown`
|===
