=== Iso8601_date_time Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_date_time*

h|*Description*
2+a|Represents an ISO 8601 date/time, including partial and extended forms.

Note that this class includes 2 deviations from ISO 8601:2004:

* for partial date/times, any part of the date/time up to the month may be missing, not just seconds and minutes as in the standard;
* the time 24:00:00 is not allowed, since it would mean the date was really on the next day.

h|*Inherit*
2+|`<<_iso8601_type_class,Iso8601_type>>`, `<<_idate_time_class,IDate_time>>`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*month_unknown* (): `<<_boolean_class,Boolean>>`
a|Indicates whether month in year is unknown.

h|*1..1*
|*day_unknown* (): `<<_boolean_class,Boolean>>`
a|Indicates whether day in month is unknown.

h|*1..1*
|*minute_unknown* (): `<<_boolean_class,Boolean>>`
a|Indicates whether minute in hour is known.

h|*1..1*
|*second_unknown* (): `<<_boolean_class,Boolean>>`
a|Indicates whether minute in hour is known.

h|*1..1*
|*is_decimal_sign_comma* (): `<<_boolean_class,Boolean>>`
a|True if this time has a decimal part indicated by ‘,’ (comma) rather than ‘.’ (period).

h|*1..1*
|*valid_iso8601_date_time* ( +
s: `<<_string_class,String>>[1]` +
): `<<_boolean_class,Boolean>>`
a|String is a valid ISO 8601 date-time, i.e. takes the form:

* YYYYMMDDThhmmss[(,&#124;.)s+][Z&#124;±hh[mm]]

or the extended form:

* YYYY-MM-DDThh:mm:ss[(,&#124;.)s+][Z&#124;±hh[:mm]]

or one of the partial forms:

* YYYYMMDDThhmm
* YYYYMMDDThh

or the equivalent extended forms:

* YYYY-MM-DDThh:mm
* YYYY-MM-DDThh

(meanings as in DV_DATE, DV_TIME) and the values in each field are valid.

h|*1..1 +
(effected)*
|*is_partial* (): `<<_boolean_class,Boolean>>`
a|True if this date time is partial, i.e. if seconds or more is missing.

h|*1..1 +
(effected)*
|*is_extended* (): `<<_boolean_class,Boolean>>`
a|True if this date/time uses ‘-’, ‘:’ separators.

h|*1..1*
|*as_string* (): `<<_string_class,String>>`
a|ISO8601 string for date/time, in format:

* `YYYYMMDDThhmmss[,sss][Z &#124; ±hh[mm]]`

or in extended format:

* `YYYY-MM-DDThh:mm:ss[,sss][Z &#124; ±hh[mm]]`

or a partial variant; see `_valid_iso8601_date_time()_` for validity.

h|*1..1*
|*has_fractional_second* (): `<<_boolean_class,Boolean>>`
a|True if the fractional_second part is signficant (i.e. even if = 0.0).

h|*1..1*
|*as_date_time* (): `<<_date_time_class,Date_time>>`
a|Convert to a native `Date_time`.

h|*Invariants*
2+a|__Year_valid__: `valid_year (year)`

h|
2+a|__Month_valid__: `valid_month (month)`

h|
2+a|__Day_valid__: `valid_day(year, month, day)`

h|
2+a|__Hour_valid__: `valid_hour (hour, minute, second)`

h|
2+a|__Minute_valid__: `not minute_unknown implies valid_minute(minute)`

h|
2+a|__Second_valid__: `not second_unknown implies valid_second (second)`

h|
2+a|__Fractional_second_valid__: `has_fractional_second implies (not second_unknown and valid_fractional_second (fractional_second))`

h|
2+a|__Partial_validity_year__: `not month_unknown`

h|
2+a|__Partial_validity_month__: `not month_unknown`

h|
2+a|__Partial_validity_day__: `not day_unknown`

h|
2+a|__Partial_validity_hour__: `not hour_unknown`

h|
2+a|__Partial_validity_minute__: `minute_unknown implies second_unknown`
|===
