=== Iso8601_date Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_date*

h|*Description*
2+a|Represents an ISO 8601 date, including partial and extended forms. Value may be:

* `YYYY-MM-DD` (extended, preferred)
* `YYYYMMDD` (compactd)
* a partial invariant.

See `Time_definitions._valid_iso8601_date()_` for validity.

h|*Inherit*
2+|`Iso8601_type`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*year* (): `Integer`
a|Year.

h|
|*month* (): `Integer` +
*_Pre_*: `not month_unknown`
a|Month in year.

h|
|*day* (): `Integer` +
*_Pre_*: `not day_unknown`
a|Day in month.

h|
|*timezone* (): `Iso8601_timezone`
a|Timezone; may be Void.

h|
|*month_unknown* (): `Boolean`
a|Indicates whether month in year is unknown. If so, the date is of the form `"YYYY"`.

h|
|*day_unknown* (): `Boolean`
a|Indicates whether day in month is unknown. If so, and month is known, the date is of the form `"YYYY-MM"` or `"YYYYMM"`.

h|(effected)
|*is_partial* (): `Boolean`
a|True if this date is partial, i.e. if days or more is missing.

h|(effected)
|*is_extended* (): `Boolean`
a|True if this date uses `'-'` separators.

h|
|*as_string* (): `String`
a|Return string value in extended format.

h|*Invariants*
2+a|*_Year_valid_*: `valid_year (year)`

h|
2+a|*_Month_valid_*: `not month_unknown implies valid_month (month)`

h|
2+a|*_Day_valid_*: `not day_unknown implies valid_day (year, month, day)`

h|
2+a|*_Partial_validity_*: `month_unknown implies day_unknown`
|===
