=== Iso8601_date_time Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_date_time*

h|*Description*
2+a|Represents an ISO 8601 date/time, including partial and extended forms. Value may be:

* `YYYY-MM-DDThh:mm:ss[,sss][Z &#124; ±hh[mm]]` (extended, preferred) or
* `YYYYMMDDThhmmss[,sss][Z &#124; ±hh[mm]]` (compact)
* or a partial variant.

See `_valid_iso8601_date_time()_` for validity.

Note that this class includes 2 deviations from ISO 8601:2004:

* for partial date/times, any part of the date/time up to the month may be missing, not just seconds and minutes as in the standard;
* the time `24:00:00` is not allowed, since it would mean the date was really on the next day.

h|*Inherit*
2+|`Iso8601_type`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*year* (): `Integer`
a|Extract the year part of the date as an Integer.

h|*1..1*
|*month* (): `Integer` +
 +
_Pre_: `not month_unknown`
a|Extract the month part of the date/time as an Integer, or return 0 if not present.

h|*1..1*
|*day* (): `Integer` +
 +
_Pre_: `not day_unknown`
a|Extract the day part of the date/time as an Integer, or return 0 if not present.

h|*1..1*
|*hour* (): `Integer` +
 +
_Pre_: `not hour_unknown`
a|Extract the hour part of the date/time as an Integer, or return 0 if not present.

h|*1..1*
|*minute* (): `Integer` +
 +
_Pre_: `not minute_unknown`
a|Extract the minute part of the date/time as an Integer, or return 0 if not present.

h|*1..1*
|*second* (): `Integer` +
 +
_Pre_: `not second_unknown`
a|Extract the integral seconds part of the date/time (i.e. prior to any decimal sign) as an Integer, or return 0 if not present.

h|*1..1*
|*fractional_second* (): `Real`
a|Extract the fractional seconds part of the date/time (i.e. following to any decimal sign) as a Real, or return 0.0 if not present.

h|*1..1*
|*timezone* (): `Iso8601_timezone`
a|Timezone; may be Void.

h|*1..1*
|*month_unknown* (): `Boolean`
a|Indicates whether month in year is unknown.

h|*1..1*
|*day_unknown* (): `Boolean`
a|Indicates whether day in month is unknown.

h|*1..1*
|*minute_unknown* (): `Boolean`
a|Indicates whether minute in hour is known.

h|*1..1*
|*second_unknown* (): `Boolean`
a|Indicates whether minute in hour is known.

h|*1..1*
|*is_decimal_sign_comma* (): `Boolean`
a|True if this time has a decimal part indicated by `','` (comma) rather than `'.'` (period).

h|*1..1 +
(effected)*
|*is_partial* (): `Boolean`
a|True if this date time is partial, i.e. if seconds or more is missing.

h|*1..1 +
(effected)*
|*is_extended* (): `Boolean`
a|True if this date/time uses `'-'`, `':'` separators.

h|*1..1*
|*has_fractional_second* (): `Boolean`
a|True if the `_fractional_second_` part is significant (i.e. even if = 0.0).

h|*1..1*
|*as_string* (): `String`
a|Return the string value in extended format.

h|*1..1*
|*add* _alias_ "+" ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_date_time`
a|Arithmetic addition of a duration to a date/time.

h|*1..1*
|*subtract* _alias_ "-" ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_date_time`
a|Arithmetic subtraction of a duration from a date/time.

h|*1..1*
|*diff* _alias_ "-" ( +
a_date_time: `Iso8601_date_time[1]` +
): `Iso8601_duration`
a|Difference of two date/times.

h|*1..1*
|*add_nominal* _alias_ "++" ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_date`
a|Addition of nominal duration represented by `_a_diff_`. See `Iso8601_date._add_nominal_()` for semantics.

h|*1..1*
|*subtract_nominal* _alias_ "--" ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_date`
a|Subtraction of nominal duration represented by `_a_diff_`. See `_add_nominal_()` for semantics.

h|*Invariants*
2+a|_Year_valid_: `valid_year (year)`

h|
2+a|_Month_valid_: `valid_month (month)`

h|
2+a|_Day_valid_: `valid_day(year, month, day)`

h|
2+a|_Hour_valid_: `valid_hour (hour, minute, second)`

h|
2+a|_Minute_valid_: `not minute_unknown implies valid_minute(minute)`

h|
2+a|_Second_valid_: `not second_unknown implies valid_second (second)`

h|
2+a|_Fractional_second_valid_: `has_fractional_second implies (not second_unknown and valid_fractional_second (fractional_second))`

h|
2+a|_Partial_validity_year_: `not month_unknown`

h|
2+a|_Partial_validity_month_: `not month_unknown`

h|
2+a|_Partial_validity_day_: `not day_unknown`

h|
2+a|_Partial_validity_hour_: `not hour_unknown`

h|
2+a|_Partial_validity_minute_: `minute_unknown implies second_unknown`
|===
