=== Iso8601_duration Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*Iso8601_duration*

h|*Description*
2+a|Represents an ISO 8601 duration.

h|*Inherit*
2+|Iso8601_type, IDuration

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_decimal_sign_comma*: `Boolean`
a|True if this time has a decimal part indicated by ',' (comma) rather than '.' (period).

h|
|*valid_iso8601_duration* (s: `String`): `Boolean`
a|String is a valid ISO 8601 duration, i.e. takes the form:

* P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]

Where each nn represents a number of years, months, etc. nnW represents a number of 7-day weeks.

Note: allowing the W designator in the same expression as other designators is an exception to the published standard, but necessary in clinical information (typically for representing pregnancy duration).

h|
|*as_string*: `String`
a|ISO8601 string for duration, in format

* P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]

h|(effected)
|*is_partial*: `Boolean`
a|Returns False.

h|(effected)
|*is_extended*: `Boolean`
a|Returns True.

h|*Invariant*
2+a|*_Years_valid_*: years >= 0

h|
2+a|*_Months_valid_*: months >= 0

h|
2+a|*_Weeks_valid_*: weeks >= 0

h|
2+a|*_Days_valid_*: days >= 0

h|
2+a|*_Hours_valid_*: hours >= 0

h|
2+a|*_Minutes_valid_*: minutes >= 0

h|
2+a|*_Seconds_valid_*: seconds >= 0

h|
2+a|*_Fractional_second_valid_*: fractional_second >= 0.0 and fractional_second < 1.0
|===
