=== Iso8601_duration Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_duration*

h|*Description*
2+a|Represents an ISO 8601 duration, which may have multiple parts from years down to seconds. The `_value_` attribute is a String in the format:

* `P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]`

NOTE: two deviations from ISO 8601 are supported, the first, to allow a negative sign, and the second allowing the 'W' designator to be mixed with other designators.

h|*Inherit*
2+|`<<_iso8601_type_class,Iso8601_type>>`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*is_extended* (): `<<_boolean_class,Boolean>>`
a|Returns True.

h|*1..1 +
(effected)*
|*is_partial* (): `<<_boolean_class,Boolean>>`
a|Returns False.

h|*1..1*
|*years* (): `<<_integer_class,Integer>>`
a|Number of years in the `_value_`, i.e. the number preceding the `'Y'` in the `'YMD'` part, if one exists.

h|*1..1*
|*months* (): `<<_integer_class,Integer>>`
a|Number of months in the `_value_`, i.e. the value preceding the `'M'` in the `'YMD'` part, if one exists.

h|*1..1*
|*days* (): `<<_integer_class,Integer>>`
a|Number of days in the `_value_`, i.e. the number preceding the `'D'` in the `'YMD'` part, if one exists.

h|*1..1*
|*hours* (): `<<_integer_class,Integer>>`
a|Number of hours in the `_value_`, i.e. the number preceding the `'H'` in the `'HMS'` part, if one exists.

h|*1..1*
|*minutes* (): `<<_integer_class,Integer>>`
a|Number of minutes in the `_value_`, i.e. the number preceding the `'M'` in the `'HMS'` part, if one exists.

h|*1..1*
|*seconds* (): `<<_integer_class,Integer>>`
a|Number of seconds in the `_value_`, i.e. the integer number preceding the `'S'` in the `'HMS'` part, if one exists.

h|*1..1*
|*fractional_seconds* (): `<<_real_class,Real>>`
a|Fractional seconds in the `_value_`, i.e. the decimal part of the number preceding the `'S'` in the `'HMS'` part, if one exists.

h|*1..1*
|*weeks* (): `<<_integer_class,Integer>>`
a|Number of weeks in the `_value_`, i.e. the value preceding the `W`, if one exists.

h|*1..1*
|*is_decimal_sign_comma* (): `<<_boolean_class,Boolean>>`
a|True if this time has a decimal part indicated by ',' (comma) rather than '.' (period).

h|*1..1*
|*to_seconds* (): `<<_real_class,Real>>`
a|Total number of seconds equivalent (including fractional) of entire duration. Where non-definite elements such as year and month (i.e. 'Y' and 'M') are included, the corresponding 'average' durations from `Time_definitions` are used to compute the result.

h|*1..1*
|*as_string* (): `<<_string_class,String>>`
a|Return the duration string value.

h|*1..1*
|*add* __alias__ "+" ( +
a_val: `<<_iso8601_duration_class,Iso8601_duration>>[1]` +
): `<<_iso8601_duration_class,Iso8601_duration>>`
a|Arithmetic addition of a duration to a duration, via conversion to seconds, using `Time_definitions._Average_days_in_year_` and `Time_definitions._Average_days_in_month_`

h|*1..1*
|*subtract* __alias__ "-" ( +
a_val: `<<_iso8601_duration_class,Iso8601_duration>>[1]` +
): `<<_iso8601_duration_class,Iso8601_duration>>`
a|Arithmetic subtraction of a duration from a duration, via conversion to seconds, using `Time_definitions._Average_days_in_year_` and `Time_definitions._Average_days_in_month_`

h|*1..1*
|*multiply* __alias__ "&#42;" ( +
a_val: `<<_real_class,Real>>[1]` +
): `<<_iso8601_duration_class,Iso8601_duration>>`
a|Arithmetic multiplication a duration by a number.

h|*1..1*
|*divide* __alias__ "/" ( +
a_val: `<<_real_class,Real>>[1]` +
): `<<_iso8601_duration_class,Iso8601_duration>>`
a|Arithmetic division of a duration by a number.

h|*1..1*
|*negative* __alias__ "-" (): `<<_iso8601_duration_class,Iso8601_duration>>`
a|Generate negative of current duration value.

h|*Invariants*
2+a|__Years_valid__: `years >= 0`

h|
2+a|__Months_valid__: `months >= 0`

h|
2+a|__Weeks_valid__: `weeks >= 0`

h|
2+a|__Days_valid__: `days >= 0`

h|
2+a|__Hours_valid__: `hours >= 0`

h|
2+a|__Minutes_valid__: `minutes >= 0`

h|
2+a|__Seconds_valid__: `seconds >= 0`

h|
2+a|__Fractional_second_valid__: `fractional_second >= 0.0 and fractional_second < 1.0`
|===
