=== Iso8601_duration Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_duration*

h|*Description*
2+a|Represents an ISO 8601 duration, which may have multiple parts from years down to seconds.

h|*Inherit*
2+|`Iso8601_type`, `IDuration`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_decimal_sign_comma* (): `Boolean`
a|True if this time has a decimal part indicated by ',' (comma) rather than '.' (period).

h|
|*valid_iso8601_duration* ( +
s: `String[1]` +
): `Boolean`
a|String is a valid ISO 8601 duration, i.e. takes the form:

* P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]

Where each nn represents a number of years, months, etc. nnW represents a number of 7-day weeks.

Note: allowing the W designator in the same expression as other designators is an exception to the published standard, but necessary in clinical information (typically for representing pregnancy duration).

.Parameters +
[horizontal]
`_s_`:: String is a valid ISO 8601 duration, i.e. takes the form:

* P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]

Where each nn represents a number of years, months, etc. nnW represents a number of 7- day weeks.

NOTE: allowing the W designator in the same expression as other designators is an exception to the published standard, but necessary in clinical information (typically for representing pregnancy duration).

h|(effected)
|*is_partial* (): `Boolean`
a|Returns False.

h|(effected)
|*is_extended* (): `Boolean`
a|Returns True.

h|
|*as_string* (): `String`
a|ISO8601 string for duration, in format

* `P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]`

h|
|*months* (): `Integer`
a|Number of months.

h|
|*years* (): `Integer`
a|Number of years of nominal 365-day length.

h|
|*weeks* (): `Integer`
a|Number of 7 day weeks.

h|
|*to_seconds* (): `Integer`
a|Total number of seconds equivalent (including fractional) of entire duration.

h|
|*minutes* (): `Integer`
a|Number of 60 second minutes.

h|
|*hours* (): `Integer`
a|Number of 60 minute hours.

h|
|*days* (): `Integer`
a|Number of 24 hour days.

h|
|*as_duration* (): `Duration`
a|Convert to a native `Duration`.

h|*Invariants*
2+a|*_Years_valid_*: `years >= 0`

h|
2+a|*_Months_valid_*: `months >= 0`

h|
2+a|*_Weeks_valid_*: `weeks >= 0`

h|
2+a|*_Days_valid_*: `days >= 0`

h|
2+a|*_Hours_valid_*: `hours >= 0`

h|
2+a|*_Minutes_valid_*: `minutes >= 0`

h|
2+a|*_Seconds_valid_*: `seconds >= 0`

h|
2+a|*_Fractional_second_valid_*: `fractional_second >= 0.0 and fractional_second < 1.0`
|===
