=== Iso8601_date Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_date*

h|*Description*
2+a|Represents an ISO 8601 date, including partial and extended forms. Value may be:

* `YYYY-MM-DD` (extended, preferred)
* `YYYYMMDD` (compactd)
* a partial invariant.

See `Time_definitions._valid_iso8601_date()_` for validity.

h|*Inherit*
2+|`Iso8601_type`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*year* (): `Integer`
a|Extract the year part of the date as an Integer.

h|
|*month* (): `Integer` +
*_Pre_*: `not month_unknown`
a|Extract the month part of the date as an Integer, or return 0 if not present.

h|
|*day* (): `Integer` +
*_Pre_*: `not day_unknown`
a|Extract the day part of the date as an Integer, or return 0 if not present.

h|
|*timezone* (): `Iso8601_timezone`
a|Timezone; may be Void.

h|
|*month_unknown* (): `Boolean`
a|Indicates whether month in year is unknown. If so, the date is of the form `"YYYY"`.

h|
|*day_unknown* (): `Boolean`
a|Indicates whether day in month is unknown. If so, and month is known, the date is of the form `"YYYY-MM"` or `"YYYYMM"`.

h|(effected)
|*is_partial* (): `Boolean`
a|True if this date is partial, i.e. if days or more is missing.

h|(effected)
|*is_extended* (): `Boolean`
a|True if this date uses `'-'` separators.

h|
|*as_string* (): `String`
a|Return string value in extended format.

h|
|*add* ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_date`
a|Arithmetic addition of a duration to a date.

h|
|*subtract* ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_date`
a|Arithmetic subtraction of a duration from a date.

h|
|*diff* ( +
a_date: `Iso8601_date[1]` +
): `Iso8601_duration`
a|Difference of two dates.

h|
|*add_nominal* ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_date`
a|Addition of nominal duration represented by `_a_diff_`. For example, a duration of `'P1Y'` means advance to the same date next year, with the exception of the date 29 February in a leap year, to which the addition of a nominal year will result in 28 February of the following year. Similarly, `'P1M'` is understood here as a nominal month, the addition of which will result in one of:

* the same date in the following month, or;
* one or two days less where the following month is shorter, or;
* in the case of adding a month to the date 31 Jan, the result will be 28 Feb in a non-leap year (i.e. three less) and 29 Feb in a leap year (i.e. two less).

h|
|*subtract_nominal* ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_date`
a|Subtraction of nominal duration represented by `_a_diff_`. See `_add_nominal_()` for semantics.

h|*Invariants*
2+a|*_Year_valid_*: `valid_year (year)`

h|
2+a|*_Month_valid_*: `not month_unknown implies valid_month (month)`

h|
2+a|*_Day_valid_*: `not day_unknown implies valid_day (year, month, day)`

h|
2+a|*_Partial_validity_*: `month_unknown implies day_unknown`
|===
