=== Iso8601_time Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_time*

h|*Description*
2+a|Represents an ISO 8601 time, including partial and extended forms. Value may be:

* `hh:mm:ss[,sss][Z&#124;±hh[mm]]` (extended, preferred) or
* `hhmmss[,sss][Z&#124;±hh[mm]]` (compact)
* or a partial invariant.

See `_valid_iso8601_time()_` for validity.

NOTE: A small deviation to the ISO 8601:2004 standard in this class is that the time `24:00:00` is not allowed, for consistency with `Iso8601_date_time`.

h|*Inherit*
2+|`Iso8601_type`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*hour* (): `Integer`
a|Extract the hour part of the date/time as an Integer.

h|
|*minute* (): `Integer`
a|Extract the minute part of the time as an Integer, or return 0 if not present.

h|
|*second* (): `Integer`
a|Extract the integral seconds part of the time (i.e. prior to any decimal sign) as an Integer, or return 0 if not present.

h|
|*fractional_second* (): `Real` +
*_Pre_*: `not second_unknown`
a|Extract the fractional seconds part of the time (i.e. following to any decimal sign) as a Real, or return 0.0 if not present.

h|
|*timezone* (): `Iso8601_timezone`
a|Timezone; may be Void.

h|
|*minute_unknown* (): `Boolean`
a|Indicates whether minute is unknown. If so, the time is of the form “hh”.

h|
|*second_unknown* (): `Boolean`
a|Indicates whether second is unknown. If so and month is known, the time is of the form `"hh:mm"` or `"hhmm"`.

h|
|*is_decimal_sign_comma* (): `Boolean`
a|True if this time has a decimal part indicated by `','` (comma) rather than `'.'` (period).

h|(effected)
|*is_partial* (): `Boolean`
a|True if this time is partial, i.e. if seconds or more is missing.

h|(effected)
|*is_extended* (): `Boolean`
a|True if this time uses `'-'`, `':'` separators.

h|
|*has_fractional_second* (): `Boolean`
a|True if the `_fractional_second_` part is significant (i.e. even if = 0.0).

h|
|*as_string* (): `String`
a|Return string value in extended format.

h|
|*add* ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_time`
a|Arithmetic addition of a duration to a time.

h|
|*subtract* ( +
a_diff: `Iso8601_duration[1]` +
): `Iso8601_time`
a|Arithmetic subtraction of a duration from a time.

h|
|*diff* ( +
a_time: `Iso8601_time[1]` +
): `Iso8601_duration`
a|Difference of two times.

h|*Invariants*
2+a|*_Hour_valid_*: `valid_hour(hour, minute, second)`

h|
2+a|*_Minute_valid_*: `not minute_unknown implies valid_minute (minute)`

h|
2+a|*_Second_valid_*: `not second_unknown implies valid_second (second)`

h|
2+a|*_Fractional_second_valid_*: `has_fractional_second implies (not second_unknown and valid_fractional_second (fractional_second))`

h|
2+a|*_Partial_validity_*: `minute_unknown implies second_unknown`
|===
