=== Iso8601_duration Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Iso8601_duration*

h|*Description*
2+a|Represents an ISO 8601 duration, which may have multiple parts from years down to seconds. Value is in format:

* `P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]`

h|*Inherit*
2+|`Iso8601_type`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*seconds* (): `Integer`
a|Number of seconds.

h|
|*fractional_seconds* (): `Real`
a|Fractional seconds.

h|
|*is_decimal_sign_comma* (): `Boolean`
a|True if this time has a decimal part indicated by ',' (comma) rather than '.' (period).

h|(effected)
|*is_partial* (): `Boolean`
a|Returns False.

h|(effected)
|*is_extended* (): `Boolean`
a|Returns True.

h|
|*months* (): `Integer`
a|Number of months.

h|
|*years* (): `Integer`
a|Number of years of nominal 365-day length.

h|
|*weeks* (): `Integer`
a|Number of 7 day weeks.

h|
|*to_seconds* (): `Real`
a|Total number of seconds equivalent (including fractional) of entire duration.

h|
|*minutes* (): `Integer`
a|Number of 60 second minutes.

h|
|*hours* (): `Integer`
a|Number of 60 minute hours.

h|
|*days* (): `Integer`
a|Number of 24 hour days.

h|
|*as_string* (): `String`
a|Return the duration string value.

h|*Invariants*
2+a|*_Years_valid_*: `years >= 0`

h|
2+a|*_Months_valid_*: `months >= 0`

h|
2+a|*_Weeks_valid_*: `weeks >= 0`

h|
2+a|*_Days_valid_*: `days >= 0`

h|
2+a|*_Hours_valid_*: `hours >= 0`

h|
2+a|*_Minutes_valid_*: `minutes >= 0`

h|
2+a|*_Seconds_valid_*: `seconds >= 0`

h|
2+a|*_Fractional_second_valid_*: `fractional_second >= 0.0 and fractional_second < 1.0`
|===
