=== ISO8601_DATE Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*ISO8601_DATE*

h|*Description*
2+a|Represents an absolute point in time, as measured on the Gregorian calendar, and specified only to the day.

h|*Inherit*
2+|ISO8601_TYPE

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*year*: `Integer`
a|Year.

h|
|*month*: `Integer` +
*_Pre_*: not month_unknown
a|Month in year.

h|
|*day*: `Integer`
a|Day in month.

h|
|*month_unknown*: `Boolean`
a|Indicates whether month in year is unknown. If so, the date is of the form “YYYY”.

h|
|*day_unknown*: `Boolean`
a|Indicates whether day in month is unknown. If so, and month is known, the date is of the form “YYYY-MM” or “YYYYMM”.

h|
|*as_string*: `String`
a|ISO8601 string for date, in format YYYYMMDD or YYYY-MM-DD, or a partial invariant. See valid_iso8601_date for validity.

h|
|*is_expanded*: `Boolean`
a|True if this date uses ‘-’ separators.

h|
|*valid_iso8601_date*: `Boolean`
a|String is a valid ISO 8601 date, i.e. takes the complete form:

* YYYYMMDD or the extended form:
* YYYY-MM-DD or one of the partial forms:
* YYYYMM
* YYYY

or the equivalent extended form:

* YYYY-MM

Where:

* YYYY is the string form of any positive number in the range “0000” - “9999” (zero-filled to four digits)
* MM is “01” - “12” (zero-filled to two digits)
* DD is “01” - “31” (zero-filled to two digits)

The combinations of YYYY, MM, DD numbers must be correct with respect to the Gregorian calendar.

h|(effected)
|*is_partial*: `Boolean`
a|True if this date is partial, i.e. if day or more is missing.

h|*Invariant*
2+a|*_Year_valid_*: valid_year (year)

h|
2+a|*_Month_valid_*: not month_unknown implies valid_month (month)

h|
2+a|*_Day_valid_*: not day_unknown implies valid_day (year, month, day)

h|
2+a|*_Partial_validity_*: month_unknown implies day_unknown
|===
