=== ISO8601_DURATION Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*ISO8601_DURATION*

h|*Description*
2+a|Represents a period of time corresponding to a difference between two timepoints.

h|*Inherit*
2+|ISO8601_TYPE

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*years*: `Integer`
a|Number of years of nominal 365-day length.

h|
|*months*: `Integer`
a|

h|
|*days*: `Integer`
a|Number of 24 hour days.

h|
|*hours*: `Integer`
a|Number of 60 minute hours.

h|
|*minutes*: `Integer`
a|Number of 60 second minutes.

h|
|*seconds*: `Integer`
a|Number of seconds.

h|
|*fractional_seconds*: `Real`
a|Fractional seconds.

h|
|*is_decimal_sign_comma*: `Boolean`
a|True if this time has a decimal part indicated by ',' (comma) rather than '.' (period).

h|
|*weeks*: `Integer`
a|Number of 7 day weeks.

h|
|*as_string*: `String`
a|ISO8601 string for duration, in format

* P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]

h|
|*valid_iso8601_duration* (s: `String`): `Boolean`
a|

h|
|*to_seconds*: `Integer`
a|Total number of seconds equivalent (including fractional) of entire duration.

h|*Invariant*
2+a|*_Years_valid_*: years >= 0

h|
2+a|*_Months_valid_*: months >= 0

h|
2+a|*_Weeks_valid_*: weeks >= 0

h|
2+a|*_Days_valid_*: days >= 0

h|
2+a|*_Hours_valid_*: hours >= 0

h|
2+a|*_Minutes_valid_*: minutes >= 0

h|
2+a|*_Seconds_valid_*: seconds >= 0

h|
2+a|*_Fractional_second_valid_*: fractional_second >= 0.0 and fractional_second < 1.0
|===
