=== Numeric Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_Numeric (abstract)_*

h|*Description*
2+a|Abstract parent class of numeric types, which are types which have various arithmetic and comparison operators defined.

h|*Inherit*
2+|`Any`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(abstract)
|*add* _alias_ "+" ( +
other: `Numeric[1]` +
): `Numeric`
a|Sum with `_other_` (commutative). Actual type of result depends on arithmetic balancing rules.

h|(abstract)
|*subtract* _alias_ "-" ( +
other: `Numeric[1]` +
): `Numeric`
a|Result of subtracting `_other_`. Actual type of result depends on arithmetic balancing rules.

h|(abstract)
|*multiply* _alias_ "&#42;" ( +
other: `Numeric[1]` +
): `Numeric`
a|Product by `_other_`. Actual type of result depends on arithmetic balancing rules.

h|(abstract)
|*divide* _alias_ "/" ( +
other: `Numeric[1]` +
): `Numeric`
a|Divide by`_other_`. Actual type of result depends on arithmetic balancing rules.

h|(abstract)
|*exponent* _alias_ "^" ( +
other: `Numeric[1]` +
): `Numeric`
a|Expontiation of this by `_other_`.
|===
