=== OBJECT_REF Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*OBJECT_REF*

h|*Description*
2+a|Class describing a reference to another object, which may exist locally or be maintained outside the current namespace, e.g. in another service. Services are usually external, e.g. available in a LAN (including on the same host) or the internet via Corba, SOAP, or some other distributed protocol. However, in small systems they may be part of the same executable as the data containing the Id.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*namespace*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Namespace to which this identifier belongs in the local system context (and possibly in any other openEHR compliant environment) e.g.  terminology ,  demographic . These names are not yet standardised. Legal values for `_namespace_` are:

* `"local"`
* `"unknown"`
* a string matching the standard regex `[a-zA-Z][a-zA-Z0-9_.:\/&?=+-]*`.

Note that the first two are just special values of the regex, and will be matched by it.

h|*1..1*
|*type*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Name of the  class (concrete or abstract) of object to which this identifier type refers, e.g. `PARTY`, `PERSON`,  `GUIDELINE`  etc. These class names are from the relevant reference model. The type name `ANY` can be used to indicate that any type is accepted (e.g. if the type is unknown).

h|*1..1*
|*id*: `<<_object_id_class,OBJECT_ID>>`
a|Globally unique id of an object, regardless of where it is stored.
|===
