=== Ordered Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_Ordered (abstract)_*

h|*Description*
2+a|Abstract parent class of ordered types i.e. types on which the ‘<‘ operator is defined.

h|*Inherit*
2+|`Any`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(abstract)
|*less_than* ( +
other: `Ordered[1]` +
): `Boolean`
a|Arithmetic value comparison. In conjunction with `=`, enables the definition of the related functions `_greater_than_()` etc. This operator may be redefined in descendants.

h|
|*less_than_or_equal* ( +
other: `Ordered[1]` +
): `Boolean` +
*_Inv_result_*: `not (other < self)`
a|True if Is current object less than or equal to `_other_`.

h|
|*greater_than* ( +
other: `Ordered[1]` +
): `Boolean` +
*_Inv_result_*: `Result = (other < self)`
a|True if Is current object greater than `_other_`.

h|
|*greater_than_or_equal* ( +
other: `Ordered[1]` +
): `Boolean` +
*_Inv_result_*: `Result = (other \<= self)`
a|True if Is current object greater than or equal to `_other_`.

h|
|*not_equal* ( +
other: `Ordered[1]` +
): `Boolean`
a|
|===
