=== Double Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Double*

h|*Description*
2+a|Type used to represent double-precision decimal numbers. Corresponds to a double-precision floating point value in most languages.

h|*Inherit*
2+|`<<_ordered_numeric_class,Ordered_Numeric>>`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*floor* (): `<<_integer_class,Integer>>`
a|Return the greatest integer no greater than the value of this object.

h|*1..1 +
(effected)*
|*add* __alias__ "+" ( +
other: `<<_double_class,Double>>[1]` +
): `<<_double_class,Double>>`
a|Double-precision real number addition.

h|*1..1 +
(effected)*
|*subtract* __alias__ "-" ( +
other: `<<_double_class,Double>>[1]` +
): `<<_double_class,Double>>`
a|Double-precision real number subtraction.

h|*1..1 +
(effected)*
|*multiply* __alias__ "&#42;" ( +
other: `<<_double_class,Double>>[1]` +
): `<<_double_class,Double>>`
a|Double-precision real number multiplication.

h|*1..1 +
(effected)*
|*divide* __alias__ "/" ( +
other: `<<_double_class,Double>>[1]` +
): `<<_double_class,Double>>`
a|Double-precision real number division.

h|*1..1 +
(effected)*
|*exponent* __alias__ "^" ( +
other: `<<_double_class,Double>>[1]` +
): `<<_double_class,Double>>`
a|Double-precision real number exponentiation.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_double_class,Double>>[1]` +
): `<<_boolean_class,Boolean>>`
a|Returns True if current Double is less than `_other_`.

h|*1..1 +
(effected)*
|*negative* __alias__ "-" (): `<<_double_class,Double>>`
a|Generate negative of current Double value.

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `<<_double_class,Double>>[1]` +
): `<<_boolean_class,Boolean>>`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|*1..1 +
(redefined)*
|*equal* __alias__ "=", "==" ( +
other: `<<_double_class,Double>>[1]` +
): `<<_boolean_class,Boolean>>`
a|Reference equality for reference types, value equality for value types.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.
|===
