=== P_BMM_SCHEMA Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*P_BMM_SCHEMA*

h|*Description*
2+a|Persisted form of BMM_SCHEMA.

h|*Inherit*
2+|P_BMM_PACKAGE_CONTAINER, BMM_SCHEMA_CORE

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*bmm_version*: `String`
a|Version of BMM model, enabling schema evolution reasoning. Persisted attribute.

h|*0..1*
|*primitive_types*: `List<P_BMM_CLASS>`
a|Primitive type definitions. Persisted attribute.

h|*0..1*
|*class_definitions*: `List<P_BMM_CLASS>`
a|Class definitions. Persisted attribute.

h|*0..1*
|*includes*: `Hash<String,BMM_INCLUDE_SPEC>`
a|Inclusion list, in the form of a hash of individual include specifications, each of which at least specifies the id of another schema, and may specify a namespace via which types from the included schemas are known in this schema.
Persisted attribute.

h|*0..1*
|*bmm_schema*: `BMM_MODEL`
a|Generated by create_bmm_schema from persisted elements.

h|*1..1*
|*state*: `P_BMM_SCHEMA_STATE`
a|Current processing state; value from P_BMM_SCHEMA_STATE.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*validate_created* +
*_Pre_state_*: state = P_BMM_PACKAGE_STATE.State_created
a|Do some basic validation post initial creation

* check that package structure is regular:
** only top-level packages can have qualified names
** no top-level package name can be a direct parent or child of another (child package must be declared under the parent)
* check that all classes are mentioned in the package structure
* check that all models refer to valid packages

h|
|*load_finalise* +
*_Pre_state_*: state = P_BMM_PACKAGE_STATE.State_validated_created
a|Finalisation work:

* convert packages to canonical form, i.e. full hierarchy with no packages with names like aa.bb.cc
* set up include processing list

h|
|*merge* (other)
a|Merge in class and package definitions from `other', except where the current schema already has a definition for the given type or package.

h|
|*validate*
a|Main validation prior to generation of BMM_SCHEMA; access to `all_schemas' allows errors to be allocated to correct schema.

h|
|*create_bmm_schema* +
*_Pre_state_*: state = P_BMM_PACKAGE_STATE.State_includes_processed
a|Generate a BMM_SCHEMA object.

h|
|*canonical_packages*: `P_BMM_PACKAGE`
a|Package structure in which all top-level qualified package names like xx.yy.zz have been expanded out to a hierarchy of BMM_PACKAGE objects.
|===
