=== P_BMM_SCHEMA Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*P_BMM_SCHEMA*

h|*Description*
2+a|Persisted form of `BMM_SCHEMA`.

h|*Inherit*
2+|`P_BMM_PACKAGE_CONTAINER`, `BMM_SCHEMA`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(redefined)*
|*primitive_types*: `List<P_BMM_CLASS>`
a|Primitive type definitions. Persisted attribute.

h|*0..1 +
(redefined)*
|*class_definitions*: `List<P_BMM_CLASS>`
a|Class definitions. Persisted attribute.

h|*0..1 +
(redefined)*
|*includes*: `Hash<String,BMM_INCLUDE_SPEC>`
a|Inclusion list, in the form of a hash of individual include specifications, each of which at least specifies the id of another schema, and may specify a namespace via which types from the included schemas are known in this schema.
Persisted attribute.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*validate_created* +
*_Pre_state_*: `state = State_created` +
*_Post_state_*: `passed implies state = State_validated_created`
a|Implementation of `_validate_created()_`

h|(effected)
|*load_finalise* +
*_Pre_state_*: `state = State_validated_created` +
*_Post_state_*: `state = State_includes_processed or state = State_includes_pending`
a|Implementation of `_load_finalise()_`

h|(effected)
|*merge* ( +
other: `P_BMM_SCHEMA[1]` +
) +
*_Pre_state_*: `state = State_includes_pending` +
*_Pre_other_valid_*: `includes_to_process.has (included_schema.schema_id)`
a|Implementation of `_merge()_`

h|(effected)
|*validate*
a|Implementation of `_validate()_`

h|(effected)
|*create_bmm_model* +
*_Pre_state_*: `state = P_BMM_PACKAGE_STATE.State_includes_processed`
a|Implementation of `_create_bmm_model()_`

h|
|*canonical_packages* (): `P_BMM_PACKAGE`
a|Package structure in which all top-level qualified package names like `xx.yy.zz` have been expanded out to a hierarchy of `BMM_PACKAGE` objects.
|===
