=== P_BMM_CLASS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*P_BMM_CLASS*

h|*Description*
2+a|Definition of persistent form of `BMM_CLASS` for serialisation to ODIN, JSON, XML etc.

h|*Inherit*
2+|`P_BMM_MODEL_ELEMENT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*name*: `String`
a|Name of the class. Persisted attribute.

h|*0..1*
|*ancestors*: `List<String>`
a|List of immediate inheritance parents. Persisted attribute.

h|*0..1*
|*properties*: `Hash<String,P_BMM_PROPERTY>`
a|List of attributes defined in this class. Persistent attribute.

h|*0..1*
|*is_abstract*: `Boolean`
a|True if this is an abstract type. Persisted attribute.

h|*0..1*
|*is_override*: `Boolean`
a|True if this class definition overrides one found in an included schema.

h|*0..1*
|*generic_parameter_defs*: `Hash<String,P_BMM_GENERIC_PARAMETER>`
a|List of generic parameter definitions. Persisted attribute.

h|*1..1*
|*source_schema_id*: `String`
a|Reference to original source schema defining this class. Set during `BMM_SCHEMA` materialise. Useful for GUI tools to enable user to edit the schema file containing a given class (i.e. taking into account that a class may be in any of the schemas in a schema inclusion hierarchy).

h|*0..1*
|*bmm_class*: `BMM_CLASS`
a|`BMM_CLASS` object built by `_create_bmm_class_definition_` and `_populate_bmm_class_definition_`.

h|*1..1*
|*uid*: `Integer`
a|Unique id generated for later comparison during merging, in order to detect if two classes are the same. Assigned in post-load processing.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_generic* (): `Boolean` +
*_Post_*: `Result := generic_parameter_defs /= Void`
a|True if this class is a generic class.

h|
|*create_bmm_class*
a|Create `_bmm_class_definition_`.

h|
|*populate_bmm_class* ( +
a_bmm_schema: `BMM_MODEL[1]` +
)
a|Add remaining model elements from Current to `_bmm_class_definition_`.
|===
