=== Real Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Real*

h|*Description*
2+a|Type used to represent decimal numbers. Corresponds to a single-precision floating point value in most languages.

h|*Inherit*
2+|`Ordered_Numeric`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*floor* (): `Integer`
a|Return the greatest integer no greater than the value of this object.

h|(effected)
|*add* _alias_ "+" ( +
other: `Real[1]` +
): `Real`
a|Real number addition.

h|(effected)
|*subtract* _alias_ "-" ( +
other: `Real[1]` +
): `Real`
a|Real number subtraction.

h|(effected)
|*multiply* _alias_ "&#42;" ( +
other: `Real[1]` +
): `Real`
a|Real number multiplication.

h|(effected)
|*divide* _alias_ "/" ( +
other: `Real[1]` +
): `Double`
a|Real number division.

h|(effected)
|*exponent* _alias_ "^" ( +
other: `Double[1]` +
): `Double`
a|Real number exponentiation.

h|(effected)
|*less_than* _alias_ "<" ( +
other: `Real[1]` +
): `Boolean`
a|Returns True if current Real is less than `_other_`.

h|(effected)
|*negative* _alias_ "-" (): `Real`
a|Generate negative of current Real value.

h|(effected)
|*is_equal* ( +
other: `Real[1]` +
): `Boolean`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|(redefined)
|*equal* _alias_ "=", "==" ( +
other: `Real[1]` +
): `Boolean`
a|Reference equality for reference types, value equality for value types.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.
|===
