=== REFERENCE_MODEL_ACCESS Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*REFERENCE_MODEL_ACCESS*

h|*Description*
2+a|Access to service interface to BMM object model.

h|*Inherit*
2+|BMM_DEFINITIONS

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*schema_directories*: `List<String>`
a|List of directories where all the schemas loaded here are found.

h|*1..1*
|*all_schemas*: `Hash<SCHEMA_DESCRIPTOR, String>`
a|All schemas found and loaded from `schema_directory'. Keyed by schema_id, i.e.

* model_publisher '_' schema_name '_' model_release

e.g. openehr_rm_1.0.3, openehr_test_1.0.1, iso_13606-1_2008. This is the same key as BMM_SCHEMA.schema_id. Does not include schemas that failed to parse (i.e. SCHEMA_ACCESS.passed = False)

h|*1..1*
|*valid_top_level_schemas*: `Hash<BMM_SCHEMA, String>`
a|Top-level (root) schemas in use. Table is keyed by logical schema_name, i.e. model_publisher '_' model_name, e.g. "openehr_rm". Schemas containing different variants of same model (i.e. model_publisher + model_name) are considered duplicates.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*initialise_with_load_list* (a_schema_dirs: `List<String>`, a_schema_load_list: `List<String>`)
a|Initialise with a specific schema load list, usually a sub-set of schemas that will be found in the directory `an_absolute_dir'.

h|
|*initialise_all*
a|

h|
|*reload_schemas*
a|
|===
