=== RESOURCE_DESCRIPTION_ITEM Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*RESOURCE_DESCRIPTION_ITEM*

h|*Description*
2+a|Language-specific detail of resource description. When a resource is translated for use in another language environment, each RESOURCE_DESCRIPTION_ITEM needs to be copied and translated into the new language.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*language*: `TERMINOLOGY_CODE`
a|The localised language in which the items in this description item are written. Coded using ISO 639-1 (2 character) language codes.

h|*1..1*
|*purpose*: `String`
a|Purpose of the resource.

h|*0..1*
|*keywords*: `List<String>`
a|Keywords which characterise this resource, used e.g. for indexing and searching.

h|*0..1*
|*use*: `String`
a|Description of the uses of the resource, i.e. contexts in which it could be used.

h|*0..1*
|*misuse*: `String`
a|Description of any misuses of the resource, i.e. contexts in which it should not be used.

h|*0..1*
|*original_resource_uri*: `List<Hash<String, String>>`
a|URIs of original clinical document(s) or description of which resource is a formalisation, in the language of this description item; keyed by meaning.

h|*0..1*
|*other_details*: `Hash<String, String>`
a|Additional language-senstive resource metadata, as a list of name/value pairs.
|===
