=== Statistical_evaluator Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*Statistical_evaluator*

h|*Description*
2+a|A basic statistical evaluator class providing common functions on collections of numbers.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*sum* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_double_class[Double^]`
a|Sum of a container of values.

h|*1..1*
|*avg* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_double_class[Double^]`
a|Synonym for `_mean()_`.

h|*1..1*
|*mean* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_double_class[Double^]`
a|Mean (arithmetic average) of a container of values.

h|*1..1*
|*median* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]`
a|Return numerically centre value in ordered form of container contents.

h|*1..1*
|*mode* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]`
a|Mode (most frequent) of a container of values.

h|*1..1*
|*max* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]`
a|Maximum of a container of values.

h|*1..1*
|*min* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]`
a|Minimum of a container of values.

h|*1..1*
|*count* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]`
a|Return the number of items in `_vals_`, i.e. `_vals.count_`.

h|*1..1*
|*std_dev* ( +
vals: `link:/releases/BASE/{base_release}/foundation_types.html#_container_class[Container^]<link:/releases/BASE/{base_release}/foundation_types.html#_numeric_class[Numeric^]>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_double_class[Double^]`
a|Compute standard deviation of a container of values.
|===
