=== VERSION_TREE_ID Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*VERSION_TREE_ID*

h|*Description*
2+a|Version tree identifier for one version. Lexical form:

`trunk_version [  '.' branch_number  '.' branch_version ]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value*: `String`
a|String form of this identifier.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*trunk_version* (): `String`
a|Trunk version number; numbering starts at 1.

h|
|*is_branch* (): `Boolean`
a|True if this version identifier represents a branch, i.e. has branch_number and branch_version parts.

h|
|*branch_number* (): `String`
a|Number of branch from the trunk point; numbering starts at 1.

h|
|*branch_version* (): `String`
a|Version of the branch; numbering starts at 1.

h|*Invariants*
2+a|*_Value_valid_*: `not value.is_empty`

h|
2+a|*_Trunk_version_valid_*: `trunk_version /= Void and then trunk_version.is_integer and then trunk_version.as_integer >= 1`

h|
2+a|*_Branch_number_valid_*: `branch_number /= Void implies branch_number.is_integer and then branch_number.as_integer >= 1`

h|
2+a|*_Branch_version_valid_*: `branch_version /= Void implies branch_version.is_integer and then branch_version.as_integer >= 1`

h|
2+a|*_Branch_validity_*: `(branch_number = Void and branch_version = Void ) xor (branch_number /= Void and branch_version /= Void )`

h|
2+a|*_Is_branch_validity_*: `is_branch xor branch_number = Void`

h|
2+a|*_Is_first_validity_*: `not is_first xor trunk_version.is_equal(“1”)`
|===
