include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ars Semantica; openEHR Foundation Management Board.

=== Contributors

This specification has benefited from formal and informal input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following people for their contributions.

* Patrick Langford, NeuronSong LLC, Utah, USA
* Claude Nanjo MA African Studies., M Public Health, Cognitive Medical Systems Inc., California, USA
* Erik Sundvall PhD, Linkoping University, Sweden

=== Trademarks

* 'openEHR' is a registered trademark of the openEHR Foundation
* 'OMG' and 'UML' are registered trademarks of the Object Management Group
== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

== Tooling

The {openehr_awb}[openEHR ADL Workbench (AWB)^] fully implements this specification, and provide a convenient way of illustrating BMM semantics. The screenshots used in this specification are all from the ADL Workbench. The tool is written in the Eiffel language, and is available as {openehr_awb_github}[open source on Github^]. The BMM libraries can be found in the {eomf_bmm}[EOMF Github repository^].

A modelling tool known as Archie implements BMM in Java, and {openehr_archie_github}[can be found in the openEHR Github area^].

:sectnums!:

include::partial$amendment_record.adoc[]
