include::partial$module_vars.adoc[]

//
// ============================================ Asciidoc HEADER =============================================
//

//
// ============================================ Asciidoc PREAMBLE =============================================
//


= {spec_title} [.spec-status.spec-status-stable]#{spec_status}#

== Purpose

This document describes a persistence model for the Basic Meta-Model (BMM) known as `P_BMM`, that may be used as a basis for serialisation of BMM models. It may be considered as an approximate replacement for the UML XMI for data-only models. It is human-readable and writable, and supports generic types (open and closed), container types, and multiple inheritance.






//
// ============================================= Asciidoc BODY ===============================================
//


//
// --------------------------------------------- Preface -----------------------------------------------
//

== Feedback

Feedback may be provided on the {openehr_lang_forum}[openEHR languages specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].


