include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ars Semantica; openEHR Foundation Management Board; (previously Ocean Informatics UK).

=== Contributors

This specification has benefited from formal and informal input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following people for their contributions.

* Kurt W. Allen, Applicadia Inc, Minnesota, USA
* Rong Chen, MD, PhD, Cambio Healthcare Systems, Sweden
* Sam Heard, MD, DRCOG, MRCGP, FRACGP, Director at Ocean Informatics, Australia
* Claude Nanjo, MA African Studies., M Public Health, Cognitive Medical Systems Inc., California, USA

=== Supporters

The work reported in this paper has been funded in by the following organisations:

* University College London - Centre for Health Informatics and Multi-professional Education (CHIME);
* Ocean Informatics.

Special thanks to David Ingram, Emeritus Professor of Health Informatics at UCL who provided a vision and collegial working environment ever since the days of GEHR (1992).

=== Trademarks

* 'openEHR' is a trademark of the openEHR Foundation
* 'Java' is a registered trademark of Oracle Corporation
* 'Microsoft' and '.Net' are trademarks of the Microsoft Corporation
== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.




:sectnums!:

include::partial$amendment_record.adoc[]
