include::partial$module_vars.adoc[]

//
// ============================================ Asciidoc HEADER =============================================
//

//
// ============================================ Asciidoc PREAMBLE =============================================
//


= {spec_title} [.spec-status.spec-status-stable]#{spec_status}#

== Purpose

This document describes the syntax of the Object Data Instance Notation (ODIN), previously known
as the 'dADL' syntax from the openEHR ADL specifications. It is intended for software developers,
technically-oriented domain specialists and subject matter experts (SMEs). ODIN is designed as a
human-readable and computer-processible data representation syntax, and can be hand-edited using a
normal text editor.

== Nomenclature

In this document, the term 'attribute' denotes any stored property of a type defined in an object
model, including primitive attributes and any kind of relationship such as an association or aggregation.
Where XML is mentioned, XML 'attributes' are always referred to explicitly as 'XML
attributes'.






//
// ============================================= Asciidoc BODY ===============================================
//


//
// --------------------------------------------- Preface -----------------------------------------------
//

== Feedback

Feedback may be provided on the {openehr_lang_forum}[openEHR languages specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].


