include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Contributors

This specification has benefited from formal and informal input from the openEHR and wider health informatics community.

=== Trademarks

* 'openEHR' is a registered trademark of the openEHR Foundation




ifdef::package_qualifiers[]
endif::[]
== Previous Versions

This specification is based on the types originally defined in the {openehr_rm_103_support}[openEHR Support Information Model from Release 1.0.3 of the Reference Model^]. Some changes have been made as follows.

=== Interval types

The additional types `Point_interval` and `Proper_interval` have been added, to support the common need for a point value and a proper interval to be specified as substitutable types. The types `Multiplicity_interval` and `Cardinality` have been added, from the {openehr_am_aom2}[AOM2 specification^].

=== Functional meta-types

A collection of meta-types representing routines, procedures and functions has been added, to support specifications that need to use these concepts. 

ifdef::package_qualifiers[]
:pkg: org.openehr.base.foundation_types.
endif::[]

:sectnums!:

include::partial$amendment_record.adoc[]
