include::partial$module_vars.adoc[]

= Primitive Types

== Overview

This section describes primitive types assumed by all openEHR models. These are types supported directly by most programing languages, and usually visible via either a class interface and/or a built-in raw value type. The following table lists the primitive types assumed by openEHR.

[cols="1,4", options="header"]
|===
|Type name +
 in openEHR |Description                                                        

|`Octet`    |a type whose value is an 8-bit value.
|`Character`|a type whose value is a member of an 8-bit character-set
             (ISO: "repertoire").
|`Boolean`  |logical True/False values; usually physically represented as an 
             integer, but need not be.
|`Integer`  |32-bit integers.
|`Integer64`|64-bit integers.                                                   
|`Real`     |32-bit real numbers in any interoperable representation, including
             single-width IEEE floating point.
|`Double`   |64-bit real numbers, in any interoperable representation including
            double-precision IEEE floating point.
|`String`   |represents unicode-enabled strings.
|===

The figure below illustrates these types. Simple inheritance relationships are shown which facilitate the type descriptions below. Actual inheritance from or subsitutability for an `Any` class is not assumed, and is shown only for convenience (e.g. to indicate that the '=' operator is available on any type). The type `Ordered_numeric` is on the other hand is used to indicate assumed substitutability of numeric types, and is intended to be mapped to an equivalent type in a real type system (e.g. in Java, `java.lang.Number`). Data-oriented implementation type systems such as XML-schema do not have such operations.

[.text-center]
.base.foundation_types.primitive_types Package
image::ROOT:uml/BASE-foundation_types.primitive_types.svg[id=foundation_types_primitive_types, align="center"]

== Unicode

It is assumed in the openEHR specifications that Unicode is supported by the type `String`. Unicode is needed for all Asian, Arabic and other script languages, for both data values (particularly plain text and coded text) and for many predefined string attributes of the classes in the openEHR Reference Model. It encompasses all existing character sets. In openEHR, UTF-8 encoding is assumed.

== Class Definitions

include::ROOT:partial$classes/boolean.adoc[]

include::ROOT:partial$classes/ordered.adoc[]

include::ROOT:partial$classes/character.adoc[]

include::ROOT:partial$classes/octet.adoc[]

include::ROOT:partial$classes/string.adoc[]

include::ROOT:partial$classes/uri.adoc[]

include::ROOT:partial$classes/numeric.adoc[]

include::ROOT:partial$classes/ordered_numeric.adoc[]

include::ROOT:partial$classes/integer.adoc[]

include::ROOT:partial$classes/integer64.adoc[]

include::ROOT:partial$classes/real.adoc[]

include::ROOT:partial$classes/double.adoc[]
