= Preface

== Purpose

This document describes a persistence model for the Basic Meta-Model (BMM) known as `P_BMM`, that may be used as a basis for serialisation of BMM models. It may be considered as an approximate replacement for the UML XMI for data-only models. It is human-readable and writable, and supports generic types (open and closed), container types, and multiple inheritance.

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_base_bmm_persistence}[{openehr_domain}/releases/BASE/latest/bmm_persistence.html].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira_prs_base}[specifications issue tracker].

== Tooling

The {openehr_awb}[openEHR ADL Workbench (AWB)] fully implements this specification, and provide a convenient way of illustrating BMM semantics. The screenshots used in this specification are all from the ADL Workbench. The tool is written in the Eiffel language, and is available as {openehr_awb_github}[open source on Github]. The BMM libraries can be found in the {eomf_bmm}[EOMF Github repository].

A modelling tool known as Archie implements BMM in Java, and {openehr_archie_github}[can be found in the openEHR Github area].