= Preface

== Purpose

This document specifies the openEHR Expression Model (EOM) and an abstract syntax, denoted the openEHR Expression Language (oEL). The EOM defines the semantics of a first order predicate style logic that can be used to express assertions (for example in archetypes) and rulesfor example in decision support situations.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^].

Releated documents include:

* The {openehr_am_aom2}[Archetype Object Model 2 (AOM2)^].
* The {openehr_cds_gdl}[Guideline Definition Language (GDL)^].

== Status

The contents of this specification were separated out from the {openehr_am_aom2}[AOM2 specification] in order to provide a common model of expressions and rules structures for AOM, GDL and other specifications requiring it.

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_expression_language}[{openehr_lang_latest_expression_language}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_lang_forum}[openEHR languages specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

