= Overview

The openEHR Expression Object Model (EOM) defines the semantics of all of the elements of computable expressions that are used in openEHR, and are likely to be used in healthcare and life sciences computing where rules and expressions are needed. The model is designed as an extensible core formalism suitable for use and extension in other formalisms.

The openEHR Expression Language (EL) specified here is an abstract syntax counterpart to the Expression Object Model, and may be considered a 'default syntax'. Other syntaxes or syntax variants are certainly possible, and other serialisation methods are possible, such as object graph serialisation into XML, JSON, YAML etc. The EL is provided firstly as a way of specifying and explaining the semantics of the EOM, and secondly, as one way of actually authoring expressions and rules in textual form. This approach is the same as with any programming language, where the usual form for learning and programming is the abstract language form, while the computational form is an abstract syntax tree (AST) or similar.

Accordingly, the EOM should be considered the normative definition of the openEHR Expression formalism, and indeed not all implementations need support the language: they might for example only serialse in JSON or use purely graphical visualisation.

[.tbd]
TBD: possibly the following is no longer true.

The formalism as defined here requires extensions for use, at a minimum to provide concrete value referencing. 
Extensions would also typically provide more operators, functions, leaf types and other features that are needed in specific circumstances.

Key features of the formalism include:

* variable declarations, assignments and expressions;
* strong typing;
* the ability to use externally defined information models;
* standard logical operators including universal and existential quantification, as well as user-defined operators;
* standard arithmetic and relational comparison operators, enabling the use of numerics;
* parentheses for overridding operator precedence;
* functions, including built-ins like `current_date`, standard functions like `max()` as well as user-defined functions.

For reasons of comprehensibility and explanation, the Expression Language is defined first in this specification.

== Design Background

The openEHR Expression formalism is based on a limited first-order predicate logic language with extensions for numeric sub-expressions. It has similarities with OMG's OCL (Object Constraint Language) syntax, and is also similar to the assertion syntax used in the <<Object_Z>> and <<Eiffel>> languages and tools for over a decade (see <<Sowa>>, <<Hein>>, <<Kilov_Ross>> for an explanation of predicate logic in information modelling). None of these languages has been used directly, for reasons including:

* OCL has a complex type system connected to the UML meta-model, and includes some undecidable procedural semantics;
* none have adequate variable referencing mechanisms, such as to paths and external queries.

There are also similarities with other languages developed in the health arena for expressing 'medical logic' (Arden <<hl7_arden>>), guidelines (<<GLIF>> and many others) and decision support (e.g. GELLO <<hl7_gello>>). These languages were not directly used, for reasons including:

* none have an easily extensible value referencing mechanism;
* some are too procedural (Arden, GLIF);
* current versions of some of these languages have been made specific to the HL7v3 RIM, a particular model of health information designed for message representation (GLIF 3.x, GELLO).

Nevertheless, various elements of Arden and GELLO provided useful inspiration for the formalism described here.

Modern syntaxes that provide a more generic and minimal inspiration for the expression syntax described here include the {xpath}[Xpath syntax].

== Requirements

The semantic requirements are for expressions including arithmetic, boolean, and relational operators, functions, logical quantifiers, operator precedence, constant values, and variables. However, there is no support in the core specification for procedural semantics or most of the other complexities of full-blown programming languages.

In addition, there is a need to be able to provide:

* multi-lingual translations for symbolic variables, in a similar way to the {openehr_am_adl2}[openEHR Archetype Definition Language (ADL)];
* bindings that connect variables to external data sources;
* an ability to use externally defined information models that supply types that may be used in EL statements.

== Design Paradigm

The assumed execution model of the Expression language is that EL statements are evaluated by an _evaluator_ against a _data context_, which determines the truth values of the expression(s). The data context is the origin for some or all of the variables mentioned in the expressions, which may be read from and written to. It may concretely be a retrieved data structure, or data via an API call to the EHR, demographics, laboratory system etc.

The data context may be specified in two ways. It may be visible within the artefact or computing context in which the EL statements appear, or it may be specified explicitly. In the first case, the EL instance is minimally a value-returning logical proposition such as `$systolic_pressure > 0`. This is shown below.

[.text-center]
.EL design structure - implicit context
image::diagrams/EL_design_structure-implicit.svg[id=EL_design_structure_implicit, align="center"]

In the explicit form, an _EL text_ consisting of multiple _statements_ and an explicit context definition is used, as shown below.

[.text-center]
.EL design structure - explicit context
image::diagrams/EL_design_structure-explicit.svg[id=EL_design_structure_explicit, align="center"]

In both cases, the result of parsing into computable form for evaluation must result in an instance of the Expression Object Model (EOM), which will include instances of BMM classes, as these are used to represent the definitions of which expression elements (function calls, variable references etc) are _uses_.

This specification first describes the elements of the EL expression syntax, then the EOM.

== Expressions and Ontic Truth

No assumption is made about whether the data context used is complete or faithful to reality. Consequently, the _expression universe_ is technically speaking an 'open world' in the sense of the {wikipedia_open_world_assumption}[open-world assumption]. However, higher-level applications or components (or users) may have sufficient knowledge about the data as to be able to treat it in a closed world fashion, for example to treat absence of X as negation of X.

