= The Expression Language

== Overview

This section describes the openEHR Expression Language. In the various contexts where openEHR expressions are used, the syntax provides a foundation for concrete  syntaxes supporting specific value-referencing mechanisms, as well as other types of rules, operands etc. The key features of the language are: variable declarations, assignments and expressions. Most of the semantics are in the expression part, which is based on first-order predicate logic with the addition of arithmetic and relational operators to enable the use of numeric elements. Expressions may contain constants, variable references, value references and functions.

== Typing

The Expression language is fully typed, with all types coming from a set of types consisting of primitive types plus an object reference type. The primitive types are shown below, along with typical literal values, which are expressed in the {openehr_odin}#_primitive_types[ODIN syntax].

[cols="1,2, 3",options="header"]
|=================================================================
|Name                   |Literal value                          |Description

| `Boolean`             |`True`, `False`                        |Boolean value
| `Integer`             |`10`, `-4`, `1024`                     |Integer value
| `Real`                |`10.0`, `0.345`                        |Real value
| `Date`                |`2004-08-12`                           |ISO8601-format date
| `Date_time`           |`2004-08-12T12:00:59`                  |ISO8601-format date/time
| `Time`                |`12:00:59`                             |ISO8601-format time
| `Duration`            |`P39W`                                 |ISO8601-format duration
| `String`              |`"this is a string"`                   |String
| `Uri`                 |`http://en.wikipedia.org/wiki/Everest` |Uri in RFC3986 format <<uri_syntax>>
| `Terminology_code`    |`[snomed_ct::2004950]`                 |Terminology code reference
|=================================================================

The special `Object_ref` type is reserved for creating references to arbitrary objects in the data context, to which some operations can be applied.

[.tbd]
TBD: do we need `Integer64` and `Real64`?

Automatic type promotion from `Integer` to `Real` applies to all integer and real values and expressions, in the same fashion as most programming languages.

== Variable Declarations, References and Assignments

Variables may be declared within a statement set, consisting of a name of the form `var` and a type. Multiple variables may be declared on the same line in the same way as in many programming languages. The following shows various declarations:

--------
    date_of_birth: Date
    age_in_years: Integer

    weight, height, bmi: Real
--------

Variables are referenced within assignments and expressions using the same syntax, i.e. `var`. 

Typically declarations are used with assignments in the same way as in general purpose programming in mainstream languages. A variable can be assigned a number of kinds of things that are useful in statement sets, including constants, expressions and value-references. A declaration can be combined with an assignment. These are illustrated below.

--------
    Mph_to_kmh_factor: Real := 1.6                 -- literal assigmment to create a constant
    speed_kmh, speed_mph: Real                     -- variable declarations
        
    speed_mph := /path/to/mph/data/value           -- (provided by an extension)
    speed_kmh := speed_mph * Mph_to_kmh_factor     -- an assertion containing variable references
--------

Above, the path `/path/to/mph/data/value` is assumed to be provided by an extension to the language, for example that enables archetype or XML data to be accessed.

== Assertions

An assertion is a standalone expression, often with a tag, which enables the meaning of the expression to be understood in context. If a tag is supplied it is prepended with a colon. The following example states that the speed in kilometres of some node is related to the speed-in-miles by a factor of 1.6:

--------
    speed_validity: speed_kmh = speed_mph * Mph_to_kmh_factor
--------

Note that the final statement here is a Boolean-returning equality expression, not an assignment. It is stating that the data items representing speed in miles per hour and km per hour are related by the conversion factor `Mph_to_kmh_factor`, which was earlier defined to be `1.6`. This is different from the last statement in the previous example, which _assigns_ the result of a multiplication to the variable `speed_kph`.

The above example could also have been achieved without variables, as follows:

--------
    speed_validity: /path/to/kmh/data/value = /path/to/mph/data/value * 1.6
--------

In both cases it represents an assertion that when evaluated may be violated, in which case the statement evaluator can generate an _assertion violation_ which might be used to notify a user or do some other action.

[.tbd]
TBD: alternative: could include the keyword `check` prior to assertion expression to make it clearer that the intention is to check that this condition holds; may also prevent confusion for readers used to languages where '=' is assignment.

== [[language-expressions]]Expressions

Expressions constitute the main part of the Expressions language, and consist of a familiar typed, tree-structured, operator-based syntax common to many programming languages and logics. The two element types are _operators_ and _operands_, i.e. leaf nodes. Expressions may contain the following elements:

* _value references_: i.e. references to data elements in the form of an archetype path;
* _literals_: i.e. primitive values including the date/time types;
* _operators_: arithmetic operators, relational operators, boolean operators, quantification operators;
* _functions_: various built-in functions as well as user-defined functions.

In the Expression language, functions are treated as lead nodes in expressions, rather than expression nodes.

=== Operands (Leaf Nodes)

Operands in an assertion expression are typed and are of four kinds, as described in the following sub-sections.

==== Literal Values

Literal values are of any primitive type, and are expressed in the {openehr_odin}[ODIN syntax]. Examples are shown above under <<Typing>>.

==== Value References and Object References

Entities in the data context can be referred to in two ways. The concrete reference mechanism must be defined in an extension; here we assume it is some kind of path of the form `/path/to/data/item`. The first kind of reference is a _value_reference_, and is achieved by the use of the naked reference. The assumption is that the reference points to a data item of a primitive type, or one that can be interpreted or converted unambiguously to a primitive type by the statement evaluator. The 'type' of any value reference is thus always a primitive type. This enables referencing to normal leaf values in the data.

The other form of reference is an _object reference_. This enables a reference to an arbitrary object within the data to be created, and is done using the form `@ref`, e.g. `@/path/to/data`. The type of this is `Object_ref` within the expression type system, and the instance represents a reference, not a value. Certain operators such as `exists` and `for_all` can be used with object references. An object reference may be created to any data entity in the data context, including primitive values.

The following shows a value reference in the form of an archetype path followed by an object reference to the same location.

--------
    /data[id2]/items[id3]/value[id35]/value     -- Date of initial onset; type = Date
    
    @/data[id2]/items[id3]/value[id35]/value    -- Object ref to 'date of initial onset' item; 
                                                -- type = Object_ref
--------

An object reference can be assigned to a variable in the normal way. This variable must have the type `Object_ref`. It can then be used in the normal way in expressions and assignments with operators that apply to object references. The following illustrates.

--------
    pregnancy_data: Object_ref := @/path/to/pregnancy/data
--------

==== Functions

Functions are considered leaf entities in the Expression language, and can be of a built-in type or external (user-defined) type. All functions are considered to have a formal typed signature of the form:

----
    <Arg1-Type, Arg2-Type, ....>: Result-type
----

Thus the integer addition function `add` would have the signature `<Integer, Integer>: Integer`.

The following functions are assumed to be built in (how particular implementations achieve this may vary).

[cols="1,1,1,2",options="header"]
|=================================================================
|Name               |Textual Rendering 	|Signature          |Meaning

4+^h|Degree 0 functions (no arguments)

|current_date       |current_date       |:Date              |Current date
|current_time       |current_time       |:Time              |Current time
|current_date_time  |current_date_time  |:Date_time         |Curent date time

4+^h|Degree N functions (N argument)

|sum                |`sum (x, y, ....)` |<Real, ...>: Real  |Equivalent to `x + y + ....`
|mean               |`mean (x, y, ...)` |<Real, ...>: Real  |The mean (average) value of x, y, ...
|max                |`max (x, y, ...)`  |<Real, ...>: Real  |The maximum value among x, y, ...
|min                |`min (x, y, ...)`  |<Real, ...>: Real  |The minimum value among x, y, ...

|=================================================================

All of the above functions which take `Real` argument will take `Integer` arguments and automatically promote them to `Real` in the usual fashion.

Externally defined functions are described below under <<language-extensions, Extensions>>.

=== [[language-operators]]Operators

Expressions can include arithmetic, relational and boolean operators, plus the existential and universal quantifiers. The full operator set is shown below, along with textual and symbolic renderings. The latter are just standard Unicode symbols. Expression parsers should ideally support these symbols as operator equivalents in addition to the textual form, since it allows expressions to be expressed in a more compact and less language-independent way.

[cols="1,1,1,3",options="header"]
|=================================================================
|Identifier         |Textual +
                     Rendering 		|Symbolic +
                                         Rendering 	|Meaning
4+^h|Arithmetic Operators - Numeric result; descending precendence order

|"exp"          | ^             |≥          |Expontentiation
|"times"        | *             |*          |Multiplication
|"divide"       | /             |/          |Division
|"mod"          | %             |%          |Modulo (whole number) division
|"plus"         | +             |+          |Addition
|"minus"        | -             |-          |Subtraction

4+^h|Relational Operators - Boolean result; equal precedence

|"eq"           | =             |=          |Equality relation between numerics
|"ne"           | !=            |≠          |Inequality relation between numerics
|"lt"           | <             |<          |Less than relation between numerics
|"le"           | \<=           |≤          |Less than or equal relation between numerics
|"gt"           | >             |>          |Greater than relation between numerics
|"ge"           | >=            |≥          |Greater than or equal relation between numerics

4+^h|Logical Operators - Boolean result; descending precendence order

|"not"          |not, ~ 		|∼, ¬ 		|Negation, "not p"
|"and"          |and 			|∧ 			|Logical conjunction, "p and q"
|"or"           |or 			|∨ 			|Logical disjunction, "p or q"
|"xor"          |xor 			|⊻ 			|Exclusive or, "only one of p or q"
|"exists"       |exists 		|∃ 			|Existential quantifier, "there exists ..."
|"for_all"      |for_all ... in |∀ ... ∈	|Universal quantifier, "for all x in y P"
|"implies"      |implies 		|⇒ 			|Material implication, "p implies q", or "if p then q"
|=================================================================

Operator semantics that require further explanation are described below.

==== Logical Negation

All Boolean operators take Boolean operands and generate a Boolean result. The `not` operator can be applied as a prefix operator to all operators returning a Boolean result as well as a parenthesised Boolean expression.

==== Logical Quantifiers

The two standard logical quantifier operators are supported, `exists`, `for_all`. Both operators are used with respect to value references within the execution data context. The `exists` operator applied to a value reference (such as a path in an information structure) state that the value is present in the data context; the negated form states that it does not exist. The following simple example illustrates.

--------
    is_female implies exists @/path/to/data/about/pregnancies

    is_female ⇒ ∃ @/path/to/data/about/pregnancies     -- symbolic form
--------

The same may be achieved using variables.

--------
    pregnancy_data: Object_ref := @/path/to/data/about/pregnancies

    is_female implies exists pregnancy_data

    is_female ⇒ ∃ pregnancy_data     -- symbolic form
--------

Similarly, the `for_all` operator is applied to value references representing sets and lists, such as referred to by a path to a multiply-valued attribute.

--------
    pregnancy_data: Object_ref := @/path/to/data/about/pregnancies

    no_premature_births := for_all p in pregnancy_data p/term > P36W

    no_premature_births := ∀ p ∈ pregnancy_data p/term > P36W     -- symbolic form
--------

==== Precedence and Parentheses

The precendence of operators follows the order shown in the operator tables above. To change precedence, parentheses can be used in the fashion typical of most programming languages, as shown below.

--------
    at_risk := weight > 120 and ( is_smoker or is_hypertensive)
--------

== [[language-extensions]]Extensions

=== Operators

=== Functions


== Natural Language Issues

[.tbd]
TBD: whether we do anything about the language dependence of expression variables.
