= Terminology

An EL Module may have a terminology defined for it, which enables natural language renderings of its symbols to be defined. This is done in exactly the same way as the definition of terms in {openehr_am_adl2}#_terminology_section[ADL2] (semantics defined by AOM2). The only difference from terminology definition in openEHR archetypes is that instead of the code names being of the form `idN`, `atN` and `acN`, they are simply the symbolic variable names. Since symbolic variables are normally defined to be meaningful in their own right (i.e. in the same way as by programmers using typical programming languages), EL Modules and expressions are readable in one language (just as say, Java library code published by Oracle) but additionally translatable for rendering purposes to any language for which there is a translation.

[source,adl]
----
openEHR-bmi.v1

language
    original_language = <[ISO_639-1::en]>
    translations = <
        ["pt-br"] = <
            language = <[ISO_639-1::pt-br]>
            author = <
                ["name"] = <"Jussara Rözsch">
                ["organisation"] = <"OpenEHR  Foundation">
                ["email"] = <"jussara.macedo@gmail.com">
            >
            accreditation = <"Medical Doctor, Psychiarist, ...">
        >
    >	
    
description
    ...

definition
    ...
    
terminology
    symbol_definitions = <
        ["en"] = <
            ["body_weight"] = <
                text = <"body weight"> 
                description = <"weight of subject body">
            >
            ["height"] = <...>
            ["bmi"] = <
                text = <"body mass index">
                description = <"body mass index">
            >
        >
        ["pt"] = <
            ["body_weight"] = <
                text = <"peso do corpo"> 
                description = <"peso do corpo do sujeito">
            >
            ["height"] = <...>
            ["bmi"] = <
                text = <"índice de massa corporal">
                description = <"índice de massa corporal">
            >
        >
    >
   
----
