= Preface

== Purpose

This document specifies the openEHR Expression Model (EOM) and an abstract syntax, denoted the openEHR Expression Language (oEL). The EOM defines the semantics of a first order predicate style logic that can be used to express assertions (for example in archetypes) and rulesfor example in decision support situations.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].

Releated documents include:

* The {openehr_am_aom2}[Archetype Object Model 2 (AOM2)].
* The {openehr_cds_gdl}[Guideline Definition Language (GDL)].

== Status

The contents of this specification were separated out from the {openehr_am_aom2}[AOM2 specification] in order to provide a common model of expressions and rules structures for AOM, GDL and other specifications requiring it.

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_expression}[{openehr_domain}/releases/RM/latest/expression.html].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira_prs_base}[specifications issue tracker].

== Conformance

Conformance of a data or software artifact to an openEHR Reference Model specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal, automated derivations from the Reference Model, ITS conformance indicates RM conformance.

