= The Expression Object Model

NOTE: the model and description shown here is first draft only

== Overview

The `expression` package defines the Expression Object Model (EOM), a model of 'statements' and 'expressions' that can be used in various contexts in openEHR, including inside archetypes and in GDL guidelines. If the Expression Language or other syntax-based artefact is used, the model described here defines the parser output in the form of an expression tree. Other openEHR models designed for a particular purpose may reuse the `expression` package and further specialise some of its types specifically intended for extension.

The package structure of the `expression` package is shown below.

[.text-center]
.base.expression Package
image::{uml_export_dir}/diagrams/BASE-expression_packages.svg[id=expression_packages, align="center"]

== Core Package

The main `expression` packages `core` and `extension` are illustrated below.

[.text-center]
.base.expression.core Package
image::{uml_export_dir}/diagrams/BASE-expression.svg[id=expression_package, align="center"]

A group of statements to be used together is formally defined as one or more `STATEMENTs` in a `STATEMENT_SET`. There are three types of statements corresponding to the classes `ASSERTION`, `VARIABLE_DECLARATION` and `ASSIGNMENT`. Assertions consist of an expression tree structure that evaluates to a `Boolean` value. The root of the tree is a descendant of the class `EXPR_ITEM` that represents a Boolean-returning operator or value. An Assertion has an optional tag, enabling it to be named. 

A `VARIABLE_DECLARATION` enables a named variable to be declared with a type, which must be one of the descendants of `EXPR_DEF_TYPE`.

The `ASSIGNMENT` class defines the usual operation of assigning a value (the `_source_` i.e. the notional right-hand side) to a variable, (the `_target_`, i.e. left-hand side). The source of an assignment can be any Expression or an `EXTERNAL_QUERY`, which are sub-types of `EXPR_VALUE`.

=== Expressions

Expressions are fully described statement values that may be evaluated internally (as compared to an external query) and are defined by the `EXPR_XXX` classes. The Expression classes model a typical evaluation tree each of whose nodes is either a leaf or an operator node. The semantics of Expressions are described in the <<_complex_expressions, Complex Expressions>> sub-section in the Language section.

In this model, 'functions' are treated as leaf nodes rather than tree nodes, which would be more typical of a functional language meta-model. The leaf node approach used here treats functions as black boxes requiring an evaluation method, enabling the main expression tree to be evaluated by use of a standard set of operators whose semantics can be safely built in.

Operator semantics are defined by the class `OPERATOR_DEF`, which includes the two attributes `_name_` and `_symbols_` which define the name of the operator and its allowable symbols respectively.

[.tbd]
TBD: could potentially separate 'text symbols' and 'math symbols' to enable rendering in different ways.

The `OPERATOR_DEF_BUILTIN` class defines a hook for implementing built-in operators, i.e. those that will be executed by fixed code within the statement evaluator, e.g. a case statement or similar that uses the implementation language native operators. 

=== Class Descriptions

include::{uml_export_dir}/classes/el_text.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/el_declaration.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_variable_declaration.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_routine_declaration.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_function_declaration.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_procedure_declaration.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/el_statement.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_assignment.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_procedure_call.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_choice_group.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_choice_branch.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_condition_group.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_condition_branch.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_decision_group.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_decision_branch.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/el_expression.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_operator.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/operator_def.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_unary_operator.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_binary_operator.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/el_leaf.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_literal.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_variable.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_bound_variable.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_function_call.adoc[leveloffset=+1]

== Typing

The `expressions.types` package is shown below.

[.text-center]
.baes.expression.types Package
image::{uml_export_dir}/diagrams/BASE-expression.types.svg[id=expressions_types_package, align="center"]

The type system of the Expression formalism is defined via the type `EXPR_TYPE_DEF` and its descendants. All types have a `_type_name_` and a `_type_anchor_`, which is a variable of the coresponding primtive type from within the openEHR `base_types` package, i.e. `Integer`, `Real`, `String`, etc. The type anchor can be used for testing assignments within the implementation. A special type `TYPE_DEF_OBJECT` is included to enable a value reference (descendant of `EXPR_VALUE_REF`) to refer to a complex object, to which some expression operators can be applied, including equality and existence. The types system is extensible, as described below.

=== Class Descriptions

include::{uml_export_dir}/classes/expr_type_def.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_boolean.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_integer.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_real.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_date.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_date_time.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_time.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_duration.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_string.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_uri.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_terminology_code.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_object_ref.adoc[leveloffset=+1]

