= The Expression Language Object Model

NOTE: the model and description shown here is first draft only

== Overview

The `org.openehr.base.elom` package defines the Expression Language Object Model (ELOM), a structural model of the openEHR Expression language. Its elements, including statements and expressions can be used in various contexts in openEHR, including inside archetypes and in GDL guidelines. If the Expression Language or other syntax-based artefact is used, the model described here defines the parser output in the form of a computable structure. Other openEHR models designed for a particular purpose may reuse the `elom` package and further specialise some of its types specifically intended for extension.

The package structure of the `elom` package is shown below.

[.text-center]
.base.elom Package
image::{uml_export_dir}/diagrams/BASE-elom-packages.svg[id=elom_packages, align="center", width="50%"]

== Module Package

The top-level construct of the ELOM is the `EL_MODULE`, representing a standalone module of meta-data, model and module references, statements and bindings. It is shown below.

[.text-center]
.base.elom.module Package
image::{uml_export_dir}/diagrams/BASE-elom.module.svg[id=elom_module, align="center", width="80%"]

[.tbd]
TBD: to be continued.

=== Class Descriptions

include::{uml_export_dir}/classes/el_module.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_model_ref.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_data_binding.adoc[leveloffset=+1]

== ELOM core: statements and expressions

The core semantics of the ELOM are defined in the `expression` and `statement` packages, shown below.

[.text-center]
.base.elom.expression and statement Packages
image::{uml_export_dir}/diagrams/BASE-elom-core.svg[id=elom_core, align="center"]

== Statements

The statements part of EL is represented by the `EL_STATEMENT` class and descendants, which represent, respectively assignments, procedure calls, and decision structures (i.e. if/then and when/then).

=== Class Descriptions

include::{uml_export_dir}/classes/el_statement.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_assignment.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_routine_call.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_procedure_call.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_choice_group.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_choice_branch.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_condition_group.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_condition_branch.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_decision_group.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_decision_branch.adoc[leveloffset=+1]

== Expressions

The expressions part of EL is represented by the `EL_EXPRESSION` class and descendants.

=== Class Descriptions

include::{uml_export_dir}/classes/el_expression.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/el_operator.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_unary_operator.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_binary_operator.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/el_terminal.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_variable_ref.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_external_ref.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_local_ref.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_constant_ref.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_function_call.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_literal.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/el_predicate.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_check.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/el_defined.adoc[leveloffset=+1]

== Typing

[.tbd]
TBD: this section probably obsolete.

The `expressions.types` package is shown below.

[.text-center]
.baes.elom.types Package
image::{uml_export_dir}/diagrams/BASE-elom.types.svg[id=elom_types_package, align="center"]

The type system of the Expression formalism is defined via the type `EXPR_TYPE_DEF` and its descendants. All types have a `_type_name_` and a `_type_anchor_`, which is a variable of the coresponding primtive type from within the openEHR `base_types` package, i.e. `Integer`, `Real`, `String`, etc. The type anchor can be used for testing assignments within the implementation. A special type `TYPE_DEF_OBJECT` is included to enable a value reference (descendant of `EXPR_VALUE_REF`) to refer to a complex object, to which some expression operators can be applied, including equality and existence. The types system is extensible, as described below.

=== Class Descriptions

include::{uml_export_dir}/classes/el_type_def.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_boolean.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_integer.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_real.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_date.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_date_time.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_time.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_duration.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_string.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_uri.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_terminology_code.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/type_def_object_ref.adoc[leveloffset=+1]

